### ISSUE TITLE
Module docs mentions features not released yet

### ISSUE THREAD

**Issue by pfernandom** [uber-go/fx#1008]
**Describe the bug**
[The official documentation on modules](https://uber-go.github.io/fx/modules.html#writing-modules) mentions the use of `fx.Private`. However, this struct is not exported in the latest released version `1.18.2`. In order to use it, one would have to use the `master` branch in the Github repo.

**To Reproduce**
Use the latest published version `1.18.2` and try to use `fx.Private` in a module, as described in the docs.

The compiler complains with:

```
Private not declared by package fx  compiler[UndeclaredImportedName]
(https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)
```

**Expected behavior**
`fx.Private` should be present.

**Additional context**
While it is understandable that some features are not released yet, either:

- The official documents shouldn't mention unreleased features
- The latest published version should include all features mentioned by the published docs

If this feature is not fully ready for production use, maybe tag an alpha version which does include it and mention it in the docs.
Thank you for all the good work!

**Comment by abhinav** [comment]
@sywhang To fix this, we can change the [docs workflow](https://github.com/uber-go/fx/blob/master/.github/workflows/docs.yml) to run only on pushes of tagged releases.

**Comment by abhinav** [comment]
I've opened #1009 in case you decide to go with option 1 above.

**Comment by sywhang** [comment]
@pfernandom sorry you ran into that; Re: Private, we'll be doing a release shortly that has this feature so please keep an eye out for that!

**Comment by pfernandom** [comment]
That was quick! Thank you for getting to this so fast.

Overall, I've been having a great experience using this tool, so I will definitely look out for this release.

Thank you!
