### ISSUE TITLE
1.19 Regression: It's impossible to shutdown from an OS signal after `startCtx` is `Done()`.

### ISSUE THREAD

**Issue by aureliar8** [uber-go/fx#1015]
**Describe the bug**
Regression: It's impossible to shutdown from an OS signal after `startCtx` is `Done()`.

**To Reproduce**
1) Start an fx app
2) Wait `startTimeout` (default is 15s).
3) Send SIGTERM to the process
4) Nothing will handle the signal and the app will not shut down

**Expected behavior**
The apps shut down correctly like it did in the previous release.

**Additional context**
This line starts the goroutine that dispatches os signals. 
https://github.com/uber-go/fx/blob/213eb869667072f220b8224d16852a81897f6011/signal.go#L118
The goroutine then blocks on 
https://github.com/uber-go/fx/blob/213eb869667072f220b8224d16852a81897f6011/signal.go#L82-L95

After the `startCtx` is `Done()`, this goroutine exits and thus there's nothing to process OS signals to initiate shutdown. 

Replacing the goroutine invocation by `go recv.relayer(context.TODO())` fixed the issue for me. The context passed here should not be `Done()` until the application stops.

**Comment by tunhvn** [comment]
I have the same issue with Fx v1.19.0, it can't shutdown with Ctrl+C signal (-INT)

Fx v1.18.2 works well.

**Comment by sywhang** [comment]
Thanks for reporting this issue folks and sorry about that regression. Will shortly roll out a patch release that addresses this issue.
