### ISSUE TITLE
Enable dark/night mode on documentation side

### ISSUE THREAD

**Issue by santosh** [uber-go/fx#1071]

**Comment by sywhang** [comment]
internal tracker: https://t3.uberinternal.com/browse/GO-2000

**Comment by sywhang** [comment]
Looked into this a bit more, seems like vuepress 2 will have this feature. It's currently in beta, so once it has an actual release, we'll switch over to vuepress 2 and add this feature in.

**Comment by santosh** [comment]
Just pinging to see if issue is still active.

Not sure if vuepress was updated with dark theme. It's shouldn't be very tough to have a JS function switch to light/dark mode. Each mode being tied to a specific css file maybe.

Not an issue for now, as I prefer using extensions like Dark Reader. This issue can be closed if not planned.

**Comment by abhinav** [comment]
This is done now: https://uber-go.github.io/fx/
