### ISSUE TITLE
Glide installing wrong version of yarpc

### ISSUE THREAD

**Issue by kwojcik** [uber-go/fx#110]
Looks like for a project that only has uberfx in its glide.yaml, that glide is not respecting fx's requirements in it's own glide.yaml.

From the current fx master `e0c5d60f3dba78297ff20b61ba1626defb86efaf` glide.yaml:
```
- package: go.uber.org/yarpc
  version: v1.0.0-rc1
```
And it's glide.lock:
```
- name: go.uber.org/yarpc
  version: 6048dff5656e15859918b9d40fdf12199d0c6e3d
```

My code's glide.yaml:
```
import:
- package: go.uber.org/fx
  version: master
```
And my glide.lock after running `glide up`:
```
- name: go.uber.org/yarpc
  version: 7c6a4c5618cb38228ef9f0eb85ea71d8fc5af2c4
```
That's an old version from halloween
```
commit 7c6a4c5618cb38228ef9f0eb85ea71d8fc5af2c4
Author: Grayson Koonce <grayson.koonce@gmail.com>
Date:   Mon Oct 31 17:08:57 2016 -0700

    Use standard library's context package (#394)
```

**Comment by breerly** [comment]
Are you using at least Glide 0.12.3?

```
glide -version
```

**Comment by glibsm** [comment]
If that doesn't work, `glide cc; rm -rf vendor/ glide.lock` is worth a shot. Sometimes glide can confuse itself with a weird state of the cache

**Comment by kwojcik** [comment]
updating glide to 0.12.3 did the trick.
