### ISSUE TITLE
doc error on [register a handler with the server]

### ISSUE THREAD

**Issue by byene0923** [uber-go/fx#1113]
**Describe the bug**
doc error

**Additional context**
[Register a handler](https://github.com/uber-go/fx/blob/master/docs/get-started/echo-handler.md), does the code on step 3  need to update?
```
func NewHTTPServer(lc fx.Lifecycle, mux *http.ServeMux) *http.Server {
  srv := &http.Server{Addr: ":8080", Handler: mux}
  lc.Append(fx.Hook{
```

**Comment by JacobOaks** [comment]
What is the doc error you're referring to?

The whole function was shown in a previous step and I assume it was cut off here because we only need to show the changed lines (the addition of `mux`).

**Comment by byene0923** [comment]
i got it, thanks a lot
