### ISSUE TITLE
Slog adapter for fx

### ISSUE THREAD

**Issue by Friedrich42** [uber-go/fx#1170]
**Is your feature request related to a problem? Please describe.**
As per go 1.21 we have slog package. I would want convenience of using my slog logger in fx without creating an adapter.

**Describe the solution you'd like**
I want fx to have a slog adapter

**Describe alternatives you've considered**
Creating my wrapper over slog and implementing all the methods like [this](https://pkg.go.dev/github.com/robbert229/fxslog) repo with 0 stars, but I don't want to do that.

**Is this a breaking change?**
We do not accept breaking changes to the existing API. Please consider if your proposed solution is backwards compatible. If not, we can help you make it backwards compatible, but this must be considered when we consider new features.

It's just an addition, so it would be totally backwards compatible

**Additional context**

**Comment by robbert229** [comment]
@Friedrich42 its pretty cool that you found my repo 😄 . With the advent of go 1.22 there isn't a reason why slog support shouldn't be added (until 1.22 was released fx still supported 1.20 which only had slog via the exp package).

**Comment by robbert229** [comment]
@Friedrich42 You can close this issue as the latest release of fx has Slog support! Hurrah!

**Comment by Friedrich42** [comment]
Thank you so much!
