### ISSUE TITLE
Enable mention-bot?

### ISSUE THREAD

**Issue by blampe** [uber-go/fx#134]
https://github.com/facebook/mention-bot

We've used this successfully to ensure the right people are looking at PRs and I think it would help a lot with cross-team collaboration.

@breerly @sectioneight thoughts?

**Comment by sectioneight** [comment]
Sounds good. How do?

**Comment by blampe** [comment]
Looks like a standard webhook, shouldn't be much trouble if you have admin on the repo https://github.com/facebook/mention-bot#how-to-use

**Comment by sectioneight** [comment]
I don't have admin anymore :(

**Comment by anuptalwalkar** [comment]
+1, also, how? 
 Our team is small right now, but this will certainly help as our codebase is growing:)

**Comment by prashantv** [comment]
Added the webhook manually

**Comment by blampe** [comment]
Woohoo! Thanks @prashantv
