### ISSUE TITLE
ModuleCreate interface

### ISSUE THREAD

**Issue by abhinav** [uber-go/fx#137]
ModuleCreateFunc is defined as,

```go
type ModuleCreateFunc func(ModuleCreateInfo) ([]Module, error)
```

This makes it ugly to have types which act as module builders. Imagine,

```go
service.WithModules(
    mymodule.Module{
        Foo: bar,
    },
)
```

You can't do that because WithModule accepts Funcs only. You'd instead have to
do the following, which is a poor API IMO.

```go
service.WithModules(
    mymodule.Module{
        Foo: bar,
    }.Create,
)
```

I propose adding a `ModuleCreator` interface. `ModuleCreateFunc` (possibly
renamed to `ModuleCreatorFunc`) then becomes one of the implementations of
that interface.

```go
type ModuleCreator interface {
    func Create(ModuleCreateInfo) ([]Module, error)   
}
```

**Comment by peter-edge** [comment]
This is now done with ModuleProvider.
