### ISSUE TITLE
Package renaming

### ISSUE THREAD

**Issue by anuptalwalkar** [uber-go/fx#146]
How do you like using `uhttp`, `ulog`, `uauth`? 
Alternate package naming - `fxhttp`, `fxlog`, `fxauth`, etc

`u`-stuff is derived from `uberfx`. Packages in Fx can be super generic to use, but often clash with golang's package names. The IDE gets confused by which package to use, and developers end up with mixed bags of object initialization.

**Comment by sectioneight** [comment]
I think it looks a bit tacky, but is useful for e.g. `ulog` for unambiguous imports. `uauth` could/should probably just be `auth`

**Comment by peter-edge** [comment]
I would vote for `fx` prefix, but should we discuss this?

**Comment by dmcaulay** [comment]
I would drop the prefix and let people alias with fx if they have an import conflict.

**Comment by dmcaulay** [comment]
If we need a prefix, then `fx`.

**Comment by breerly** [comment]
Closing - these packages are moving to their own repos, as reflected in the `modular` branch.
