### ISSUE TITLE
Rename interceptor/filter terminology

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#171]
Before going 1.0, YARPC renamed the terms interceptor and filter to:

```
inbound middleware
outbound middleware
```

Why? We found that in introducing the interceptor/filter concept, that we were having to say "inbound/outbound middleware" anyways. This is because, without doing that, people were confused and didn't understand what these things did right away.

Of course, inbound and outbound middleware is much more verbose, which is why we started out with interceptor/filter in the first place, and because these are relatively common terms. In the end, we are happy we made the tradeoff, because the verbosity only occurs while setting up the framework, and not during request time.

The result has been great - users "get it" right away because the term is self describing and well understood. No need to define the term every time it's being used.

What do you say about using these terms in UberFx as well, so that both projects share terminology? I imagine this can only help our customers, where as having separate terms would only conflate the space.

cc @abhinav @kriskowal @willhug @bombela @blampe @prashantv @akshayjshah

**Comment by glibsm** [comment]
linkerino #170

**Comment by breerly** [comment]
One more note - filters and interceptors *are* pretty common in other frameworks, except that we found that in practice their direction and semantics are not as well understood as middleware. Some camps of developers get it (we certainly did), but we found that our customers at large had a much easier time with the "middleware" terminology.

**Comment by glibsm** [comment]
@breerly we've discussed this internally as a team and agree with your findings. We'll take it on to move away from interceptor/filter and clean up the API to be consistent with yarpc.

**Comment by breerly** [comment]
Oh nice - this is good stuff 👍

**Comment by breerly** [comment]
Looks like this is resolved now?

**Comment by glibsm** [comment]
@breerly Negative. Our http module is still called a Filter, just haven't gotten to it yet.

**Comment by yutongp** [comment]
close #271

**Comment by glibsm** [comment]
thank you @yutongp
