### ISSUE TITLE
Rename stdlibErr to stdliberr or stderr

### ISSUE THREAD

**Issue by yutongp** [uber-go/fx#234]
for https://github.com/uber-go/fx/blob/master/ulog/log.go#L24

[package-names](https://blog.golang.org/package-names): "Good package names are short and clear. They are lower case, with no under_scores or mixedCaps."

I like this convention because I know package names are all lower case so I can seperate them from private struct defined somewhere else. I think this convention applies to rename package as well.

So maybe 'stdliberr' or 'stderr'?

**Comment by sectioneight** [comment]
@alsamylkin

**Comment by alsamylkin** [comment]
https://github.com/uber-go/fx/pull/235
