### ISSUE TITLE
Simplify UberFx Modules

### ISSUE THREAD

**Issue by dmcaulay** [uber-go/fx#246]
Disclaimer: These are opinions based on a superficial overview of the UberFx source code.

I have two concerns when it comes to UberFx code complexity.

1. Startup doesn't need to be asynchronous. There is a lot of code for synchronizing multithreaded startup. This seems unnecessary for a couple reasons:

    * Startup isn't that slow.
    * If startup for a module is too slow, then you can distribute using roles.

2. Modules shouldn't worry about managing their backend. This is not natural and it's difficult to test. I'd prefer to formalize backends and make initialization more explicit. Here's some pseudocode illustrating this startup flow:

```
h := host.New(...)

// initialize observer with host
o := newObserver(h)

// add modules synchronously
backends := map of backends
for _, newModule := range modules {
  m := newModule(h)
  b, ok := backends[m.Backend()]
  if !ok {
    // get backend constructor from map of registered constructors
    newBackend, ok := backendConstructors[m.Backend()]
    if !ok {
      return nil, errors.New("unknown backend")
    }
    var err error
    if b, err = newBackend(h); err != nil {
      return nil, err
    }
    backends[m.Backend()] = b
  }
  err = b.AddModule(m)
  // handle error
}

// when we start we start backends
for _, b := range backends {
  err := b.Start()
  // handle error
}
```

Let's take a look at what the YARPC backend might do:

```
func New(h service.Host) *backend {
  // adjust configuration
  // initialize dispatcher
}

func (b *backend) AddModule(m service.Module) error {
  // maybe type assert to thrift module so it get access the thrift service
  // register service handler
}

func (b *backend) Start() error {
  // start dispatcher
}
```

This way we don't have to check if the dispatcher has already been initialized, started, stopped in the module functions. We can eliminate all that logic completely and rely on UberFx to startup backends responsibly. The module code also becomes simpler, because all it needs to do is create the thrift service.

I may be trivializing things, but I think separating concerns when it comes to backends and modules could help simplify other modules as well.

**Comment by sectioneight** [comment]
cc @peter-edge who is has similar thoughts

**Comment by peter-edge** [comment]
@dmcaulay check out https://github.com/uber-go/fx/pull/244, I'll see if I can put something together tomorrow to merge this

**Comment by peter-edge** [comment]
*merge this = simplify module and incorporate this too

**Comment by glibsm** [comment]
post #244 merge, are there still remaining action items?

**Comment by peter-edge** [comment]
@dmcaulay ping

**Comment by dmcaulay** [comment]
Thanks for all the work on this @peter-edge

**Comment by peter-edge** [comment]
Lol np, just making sure the comment about asynchronous startup was ok with you, this wasn't changed.

**Comment by dmcaulay** [comment]
Removing channels from the Module Interface is good enough :+1:.

Synchronous startup is part of a different issue: locks in the base module. I think Fx modules are mostly about handling requests from different sources. If we have thread safe start/stop and Fx stopped sending requests before stopping the module, then we wouldn't need a lock in the base module.

**Comment by dmcaulay** [comment]
I don't like the running state either 😀. I don't think modules really need to care about that. They're usually stopping a lower level client that takes care of the running state. Our Fx service could easily manage the state if we need it at that level.

We want to make adding Modules as easy as possible. Locking isn't that hard, but I'd prefer if people didn't have to think about it when they're creating a module. I don't think any of our modules are using the isRunning field.
