### ISSUE TITLE
Too many ways to create server.Owner

### ISSUE THREAD

**Issue by yichengq** [uber-go/fx#270]
The documented way is:
```
  svc, err := service.WithModules(
    rpc.ThriftModule(
      rpc.CreateThriftServiceFunc(NewYarpcThriftHandler),
      modules.WithName("keyvalue"),
    ),
  ).Build()
```

Besides this, it support to use `Builder`:
```
builder := server.NewBuilder().WithModules(
    rpc.ThriftModule(
      rpc.CreateThriftServiceFunc(NewYarpcThriftHandler),
      modules.WithName("keyvalue"),
    ),
)
svc, err := builder.Build()
```

and using Owner:
```
owner, err := service.New()
err = owner.AddModules(
    rpc.ThriftModule(
      rpc.CreateThriftServiceFunc(NewYarpcThriftHandler),
      modules.WithName("keyvalue"),
    ),
)
```

All three ways look pretty similar, but all different.

I think a good practice is to provide one full-featured build path, and probably provide one shortcut for fast coding. Too many building ways make developers write divergent code and increase the difficulty to read across many repos. My proposal is to
1. remove `Builder` struct
2. rename `service.New` to `server.NewOwner`
3. add new shortcut function `service.ServeModule(module ModuleCreateFunc, options ...Option) error`

Any thoughts? I can send diff if this sounds good.

**Comment by sectioneight** [comment]
Hmm, I don't think `AddModules` should be encouraged. I don't personally have a problem with the first two though. Technically we document the `NewBuilder()` in godoc but our current documentation internally goes straight for `WithModules`.

You're right that this needs some iteration though.

**Comment by sectioneight** [comment]
Also, can you please follow the instructions (that we just put up today) for internal prioritization? t.uber.com/fx -> feedback (menu item) -> issues
