### ISSUE TITLE
dig: README examples not idiomatic

### ISSUE THREAD

**Issue by glibsm** [uber-go/fx#285]
Need to take a pass. Includes things like:

```go
err := dig.Resolve(&o) // notice the pointer to a pointer as param type
if err == nil {
    // o is ready to use
}
```

```
err = g.Resolve(&f1)
require.NoError(t, err)
```

**Comment by dmcaulay** [comment]
I'd like to see some guidelines for usage in the docs. I started to integrate dig into one of my projects and found myself trying to solve the wrong problems with dig. Here are a couple rules I've started to form:

* Dependency injection should only be used to resolve dependencies at service startup.
* Application code should receive dependencies in their constructors and not use dig.Resolve directly.
* Tests should create dependencies manually and pass them into service constructors.

I'd also like to see recommendations on where dig.Register code should live.

Dependency injection is very cool, but without better guidelines it might start leading to magical and messy code that's difficult to manage.

Feel free to strongly disagree with any of this :smiley:.

**Comment by anuptalwalkar** [comment]
`Application code should receive dependencies in their constructors and not use dig.Resolve directly.
`
This gets tricky when you have a list of dependency to be consumed. May be worthwhile to investigate intelligent way to perform `dig.Resolve()`.

**Comment by glibsm** [comment]
moved to https://github.com/uber-go/dig/issues/1
