### ISSUE TITLE
move uhttp/client into uhttp

### ISSUE THREAD

**Issue by yutongp** [uber-go/fx#298]
After the middleware renaming, I feel it is quite nature to move `uhttp/client` into `uhttp`.
some of my thoughts:
1. All uhttp APIs are in one package like std http and xhttp. it will be more easier to read through the APIs.

2. `client` is a package name you may want to avoid to use for public facing. Because it is a common package name and even common variable name. an example is our doc example:
    ```golang
    client := client.New(svc)
    // client package cannot be used in this scope anymore!
    ```
   It is also not specific about what client it is. So when our users use it, they probably gonna rename it to something like `uhttpclient`.

3. `Filter`s have not naming overlap now. So it is more nature to have both `InboundMiddleware` and `OutboundMiddleware` live in the same package.

Overall, only two public APIs will be changed:
`New` -> `NewClient` and `Executor` -> `OutboundExecutor`

Let's discuss about this change. Maybe there are some good reasons to keep them in `client` package.

**Comment by yutongp** [comment]
Comments from @madhuravi:

To give you the context, I originally had client as part of the http package and moved it to it's own client package on @glibsm 's recommendation. The reasoning behind it was we now have a lot of client prefixed objects (NewClient, clientMiddleware etc.) and it made sense to strip the client and just move to it's own package.
You have some good points but I don't find them convincing enough to make this change.

A package http and http/client seems pretty intuitive to me in terms of reading the APIs.
It's totally fine for users to alias the name to uhttpclient if there are conflicts. This reminds me of config (jaeger config, uconfig, yarpc config etc.) and if we use more than one in a file, we alias the import and that's fine.
I prefer Middleware under client to OutboundMiddleware. It's much simpler to understand and follow. You have http Middleware and also http/client Middleware. It's straightforward to co-relate that to server and client.
Also side note, this would have been better started off as an issue, resolve the discussion there and then open a PR based on the conclusion.

**Comment by yutongp** [comment]
@madhuravi  thanks you for comments and suggestions. Moved this discussion to an Issue first.

0. Right now, I don't see many client prefixed objects in the code. In #289, `NewClient` is the only thing I need to add `Client` in the name. Even for local, private field, variable I didn't need to add the prefix. Maybe there is plan to add more stuffs, may potential have `client` prefix? Maybe @glibsm have more context here. If we plan to introduce more struct and API which have to add `Client` in the name, that is definitely a down vote for moving client back.

1. I agree the http and http/client seems straightforward, but when someone use it: `client := client.New(svc)`, I would have to ask what client? cassandra client? cherami client?
It almost fail into the same bucket of `util`, `misc` where naming are too generic to distingue form one or other.

2. Let me explain my thoughts over this problem.
First, I think if all users need to rename a package name, why we design a package name which all users have to rename every time when they use it in first place? We would love to make our users life easier, and give the package a better name.
Second, when users rename a package name, the name they use become inconsistent with each others, I see jaeger config has so many different names in different services: `jconfig`,` jaegerconfig`, `jaegerCfg`, `jaegercfg` etc. This break the agreement of package name. If I use the same packages as same other devs, I have to read through all their rename first and force myself to learn it.

    Here is a snap from https://blog.golang.org/package-names:
    > Avoid unnecessary package name collisions. While packages in different directories may have the same name, packages that are frequently used together should have distinct names. This reduces confusion and the need for local renaming in client code. For the same reason, avoid using the same name as popular standard packages like io or http.

   so I think  (jaeger config, uconfig, yarpc config etc.) are frequently used together, so they probably should avoid name collisions. I think we should consider doing the right thing, instead of follow them.

3. As discussed in #171, I think the most important goal is share the same terminology. Our users will speak the same words in `uhttp` and `yarpc`, `InboundMiddleware` and `OutboundMiddleware` and that is it. Hopefully, one day they will all adopt the terminology. And then, `yarpc.InboundMiddleware`, `yarpc.OutboundMiddleware`, `uhttp.InboundMiddleware`, `uhttp.OutboundMiddleware` are more straightforward compare to `uhttp.Middleware` and `client.Middleware`.

**Comment by madhuravi** [comment]
0. That's correct Yutong. When we started out, we had the client prefix, and not the outbound prefix. So imagine everything Outbound* used to be with Client* :) I was giving you the history behind the change.
1/2. I think these are the same so replying together. You have a great point there. I am not fond of all the config packages, it does get very confusing with multiple config packages around even if we can rename them. In this case, none of those are named client, yarpc service Hello has a helloClient.New, and cherami has a cherami.NewHyperbahn client. So there aren't existing conflicts in this particular case though I do agree with the philosophy.
3. True, this is the biggest point. I think ClientFilter is more intuitive than OutboundMiddleware but we adopted the middleware terminology to be consistent with YARPC. Now it would be uhttp.NewClient(uhttp.WithOutboundMiddleware) versus client.New(client.Middleware). It becomes a lot more verbose.

Will bring this up with the team as well and get back to you.

**Comment by madhuravi** [comment]
Sorry about the delay on this Yutong. Discussed this with the team. Http client does not really belong in modules. We are planning to move it out into clients/uhttp.

Since it is in it's own package, outbound prefix is not required.

@alsamylkin @anuptalwalkar @glibsm @sectioneight

**Comment by madhuravi** [comment]
Fixed by https://github.com/uber-go/fx/pull/420
