### ISSUE TITLE
dig: register service.Host in the default graph on start

### ISSUE THREAD

**Issue by glibsm** [uber-go/fx#302]
Most handlers require access to the host to get to metrics, logging and config. 

On successful uberfx service start, we should inject that into the default graph so writing handler constructors becomes a lot easier.

Open to discussion if we don't think that's a good thing to do.

**Comment by peter-edge** [comment]
See my general dislike of globals https://github.com/uber-go/fx/issues/306 heh

**Comment by glibsm** [comment]
This is going to take a different shape, global graph is going away.
