### ISSUE TITLE
Rename Manager.Start to Manager.Run, and Manager.StartAsync to Manager.Start?

### ISSUE THREAD

**Issue by peter-edge** [uber-go/fx#321]
Might be nice. Note this will break like everyone's usage of FX right now, so not so nice. Point being, `Start` isn't really just starting it, I want it to be clear that it's blocking from the name. `Serve` might also work.

**Comment by sectioneight** [comment]
Can you use our internal feedback instructions? Split brain between JIRA and GH issues means we likely will miss or misprioritize these
