### ISSUE TITLE
rpc.YARPCModule strongly depends on Thrift

### ISSUE THREAD

**Issue by peter-edge** [uber-go/fx#332]
Re: https://github.com/uber-go/fx/issues/267, the yarpc Module create function should not depend on a specific encoding @breerly

**Comment by breerly** [comment]
That is correct. Hoping to solve this after go.uber.org/yarpc/x/config has been integrated.

If we do this right, UberFX should have access to all of YARPCs encodings. When we add proto for example, that should just work in UberFX.
