### ISSUE TITLE
Panic: config value conversion

### ISSUE THREAD

**Issue by biefy** [uber-go/fx#336]
While trying to load an integer string to a float64 configuration value, config.Value.PopulateStruct() simply panic:
```
panic: interface conversion: interface is int, not float64
goroutine 1 [running]:
panic(0x984040, 0xc420231ec0)
  /usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500
go.uber.org/fx/config.convertValueFromStruct(...)
  go.uber.org/fx/config/value.go:352
go.uber.org/fx/config.Value.valueStruct(...)
  go.uber.org/fx/config/value.go:513
go.uber.org/fx/config.Value.PopulateStruct(...)
  go.uber.org/fx/config/value.go:400
go.uber.org/fx/config.Value.valueStruct(...)
  go.uber.org/fx/config/value.go:524
go.uber.org/fx/config.Value.PopulateStruct(...)
  go.uber.org/fx/config/value.go:400
go.uber.org/fx/config.Value.valueStruct(...)
  go.uber.org/fx/config/value.go:524
go.uber.org/fx/config.Value.PopulateStruct(...)
  go.uber.org/fx/config/value.go:400
```

A value in the form of an integer, e.g. "1" should be seamlessly converted to a float value with no issue. 

Also, it took me quite a while to figure out the actual offending key.  It would have saved me the time if key name is part of the failure message.

To reproduce the problem, simply create a config struct containing a float64 member, then call Value.PopulateStruct() to feed that value with any config provider reading data from an integer string.

**Comment by sectioneight** [comment]
Moved to JIRA
