### ISSUE TITLE
Rebrand uhttp as web or browser

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#374]
Having an http module in UberFX is confusing when YARPC also supports http. 

Our customers will likely think "When do I use one over the other?". The answer is that all RPC traffic will go over YARPC, while browser applications will use the uhttp module. We can make this a bit more obvious by renaming the uhttp module.

My suggestion is `web`, but I think that `browser` could work as well. Something that makes it obvious that the intention of the module is to build browser applications.

**Comment by dmcaulay** [comment]
I understand the concern, but naming to `web` or `browser` seems a little drastic. Is the HTTP module really only intended for browser applications? Does the Fx recommend YARPC for consumers who want JSON APIs? YARPC is currently described as Thrift RPC for microservices in the Fx docs. Should we expand on that?

**Comment by breerly** [comment]
Hey @dmcaulay, I'm actually recapping a point we've already discussed with the team, just didn't want to forget about it.

For API traffic, YARPC should be used. The uhttp module, according to the UberFX guys, is not intended to compete with YARPC, but to offer options to those building web applications.

**Comment by breerly** [comment]
YARPC offers raw, json, and Thrift. 

Pete just landed a change that should make all of those available.

**Comment by dmcaulay** [comment]
Cool. In that case, my misunderstanding simply validates the issue 😄.

**Comment by alsamylkin** [comment]
I would argue against "rebranding", because, well, it is the http protocol and it comes from the standard library: constructing clients is as easy as uhttp.New/copy url in a browser/every other language has it. Web or browser is too misleading...

On the other hand, I would wholeheartedly support to default to YAPRC because of type safety and promote to use it everywhere in docs, comments, etc.

The only thing for I can think of is utilitarian: providing a common middleware only with YARPC will be much easier, thus discouraging from the use of the current uhttp module and keeping parity between them.

**Comment by dmcaulay** [comment]
I think better docs could be sufficient. Naming it http makes sense to me. The http module docs should state that the YARPC module is recommended for HTTP APIs.

**Comment by madhuravi** [comment]
Agree with Dan and Alex. uhttp and yarpc docs is a good place to make this clear. web/browser has the right intent but could confuse users more. Let's keep it at uhttp and add more clarification in docs.

**Comment by breerly** [comment]
I worry about config - this is going to throw people for a loop:

```
modules:
  http:
    port: 8080
  yarpc:
    name: hello
    inbounds:
      http:
        address: ":8086"
    outbounds:
      hello:
        http:
          host: localhost
          port: 8086
```

I hear you on docs, but I'm not sure that will help here...

**Comment by dmcaulay** [comment]
is this a realistic scenario?

**Comment by breerly** [comment]
It's not obvious to me that it isn't - why shouldn't an UberFX customer use multiple modules at once?

**Comment by breerly** [comment]
If I see a service with the http config at top level, I'm going to assume that's how to configure http for the service, regardless of whether it's for API traffic (YARPC) or unstructured traffic (uhttp).

So, while I'm happy to have this convo here, this is something the UberFX team *already* agreed to.

**Comment by madhuravi** [comment]
Grayson's use case is valid IMO. One way to distinguish is to make the key name "uhttp" to match the uberfx module:
```
modules:
  uhttp:
    port: 8080
  yarpc:
    name: hello
    inbounds:
      http:
        address: ":8086"
```

What do you think Grayson? Also not sure which conversation you're referring to, we can chat offline tomorrow, maybe I'm missing something.

**Comment by breerly** [comment]
That's certainly an improvement - let's start there!

**Comment by madhuravi** [comment]
Done. Config keys are now uhttp and will go out with beta2.
