### ISSUE TITLE
Switch from Travis to CircleCI 2.0

### ISSUE THREAD

**Issue by peter-edge** [uber-go/fx#393]
I'm not sure if this should be filed here or JIRA, let me know.

CircleCI just released their beta recently which includes support for docker image caching. Given that we are moving to doing ci builds within a docker container, this should significantly speed up the build. I use CircleCI for all my personal projects and generally prefer it over Travis, I'd like to switch to it. This requires someone with admin permissions on uber-go to allow CircleCI.

https://circleci.com/beta-access
https://circleci.com/docs/2.0

@prashantv @sectioneight @glibsm @breerly

**Comment by breerly** [comment]
Does this approach work?

https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

**Comment by peter-edge** [comment]
I'm testing a version of that now.

**Comment by peter-edge** [comment]
I still rather use CircleCI but just my two cents :)

**Comment by glibsm** [comment]
I think this a discussion that's larger than just in the context of UberFx

**Comment by breerly** [comment]
Closing - this lib is getting small enough that Travis is "good enough" for now.
