### ISSUE TITLE
Support for HTTP module with Auth and non Auth clients?

### ISSUE THREAD

**Issue by dbainbridge** [uber-go/fx#425]
My service exposes both authenticated and non-authenticated HTTP endpoints.  The `defaultInboundMiddlewareChainBuilder` is automatically adding auth client from the `service` level and `uauth` appears to only allow a single auth client per service. 

Is there a way for me to provide both authenticated and non-authenticated endpoints without checking for specific paths in a custom auth client?

**Comment by sectioneight** [comment]
Yes, we're reviewing our middleware strategy both for HTTP and YARPC to figure out the best way to express endpoint-specific middlewares/decorators/interceptors/whatever-you-call-them. Will have a better story at the end of this week, and have something before the 1.0 release that allows endpoint-specific auth (and other middleware) configuration for both uhttp and yarpc modules.

**Comment by breerly** [comment]
Closing - auth will be implemented as a module in a separate repo.
