### ISSUE TITLE
dig: Externalize

### ISSUE THREAD

**Issue by abhinav** [uber-go/fx#429]
We should move dig to its own repo (go.uber.org/dig perhaps). This is probably
already on your roadmap but I wanted to explicitly create an issue to track
this.

**Comment by glibsm** [comment]
@abhinav correct, the transition is currently in the process :)

**Comment by breerly** [comment]
@glibsm wouldn't hurt to get a PR submitted to https://github.com/uber/go.uber.org ahead of time so you don't have to wait when it's time to rename the import paths.

**Comment by glibsm** [comment]
🎉 https://github.com/uber-go/dig
