### ISSUE TITLE
Logger in host interface

### ISSUE THREAD

**Issue by DAddYE** [uber-go/fx#470]
Hi all,

We have in the Host interface:

* metrics
* config
* trace
... more

Why not logging?

Took me 2 hours to realize that the `service.WithModule().Build()` initialize the `zap` global logger for us. 

Now I do:

```go
	// Initialize the service
	svc, err := service.WithModule(
		yarpc.New(yarpc.ServiceCreateFunc(server.NewYARPCThriftHandler)),
	).Build()
	if err != nil {
		panic(err)
	}

	log := zap.S()

	log.Info("Loading providers ", app.Config.Providers)
	log.Info("Starting the service ", svc.Name())
	svc.Start()
```

Why not expose `zap.L()` and `zap.S()` in the `svc` instance?

In this way I can "kind of" use `svc` as only dependency.

**Comment by glibsm** [comment]
@DAddYE Thanks for the feedback, that's a good point.

I believe we started out with the logger on the `Host` interface but it was removed during the transition to context-aware logging. Zap 1.0 release reverted a lot of our custom `ulog` code and looks like the logger lost it's home.

We'll see about adding it back before the next release to make it easier for the owners in the mean time.

The good news is that a lot of the Host interface is going to disappear soon and you will be able to dependency inject all of its existing components into your handlers and/or other custom structs. That prototyping and proofing work is currently in progress and is expected to finish before the final release of 1.0

**Comment by DAddYE** [comment]
Thanks for the answer!

> The good news is that a lot of the Host interface is going to disappear soon and you will be able to dependency inject all of its existing components into your handlers and/or other custom structs

So it is better if I don't pass now svc (service.Host) as dependency? Do you guys suggest to pass: metrics, logger, tracer etc... separately?

**Comment by glibsm** [comment]
I think it's better to pass components of service.Host individually into the appropriate places. For example, if you piece of service code requires metrics and config, pass in `Metrics()` and `Config()` from the `service.Host` into that code.

Accepting `service.Host` as a parameter is very confusing because it's not immediately clear which pieces are required.

It will also make your code easier to test.

**Comment by akshayjshah** [comment]
Since we've taken a completely different direction with the RC series of releases, this isn't relevant anymore. Luckily, this problem is solved much more neatly - it's now easy to inject anything anywhere.
