### ISSUE TITLE
App.Start/Stop to set their own default deadlines

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#496]
Instead of only having default deadlines created when calling RunForever, I'd like to:

1. Make `context.Context` optional when calling Start/Stop by creating an `fx.WithContext` option
2. When the `fx.WithContext` option is not provided, Start/Stop will create their own context with default deadlines.

This would effectively make the common case:

```go
app := fx.New()
app.Start()
app.Stop()
```

Where the context could be specified manually when needed:

```go
app := fx.New()
app.Start(fx.WithContext(context.WithTimeout(context.Background(), time.Second*5)))
app.Stop(fx.WithContext(context.WithTimeout(context.Background(), time.Second*10)))
```

This balances the API because:

* Makes Start/Stop less reliant on being called by RunForever, since they effectively set their own deadlines. 
* Keeps RunForever as a convenience, but doesn't force Start/Stop to be difficult just so RunForever can seem convenient

**Comment by akshayjshah** [comment]
Think we've already narrowed the dev experience gap between run and start/stop, but let's leave this open until we commit to a 1.0.

**Comment by breerly** [comment]
I'm going to say that the current API is just fine!
