### ISSUE TITLE
Make way for options in fx.New

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#497]
Currently, there is no way to inject anything other than constructors into `fx.New`.

This is a really nice UEX, until we *need* to inject something. For example, we *need* to be able to inject a logger. In the future, I could see us needing even more.

We should make this API future-proof. Here's a strawman to get the convo going:

```go
app := fx.New(
  fx.WithLogger(logger),
)
app.Provide(const1, const2, const3)
app.RunForever()
```

Thoughts?

**Comment by alsamylkin** [comment]
Yes, please! This way is going to be easier to have e.g. timeouts, override some components, extend the app in the future.

```golang
func WithStartTimeout(duration time.Duration) func(app *fx.App) {
     app.startTimeout = duration
}

func WithComponents(components ...interface{}) func(app *fx.App){
   app.container.Provide(components...)
}
```

**Comment by breerly** [comment]
I'm going to have a PR up for this tomorrow, along with testing for logging.
