### ISSUE TITLE
fx.In alias for dig.In

### ISSUE THREAD

**Issue by abhinav** [uber-go/fx#502]
Creating this to track adding an `In`/`Param` alias for `dig.In` to Fx. Users
of Fx should use `fx.In` or `fx.Param` instead of `dig.In`.

**Comment by breerly** [comment]
Been thinking about this for awhile... I'm actually not sold on the alias.

Most service code wont use `dig.In` or `dig.Out`. If they wanted to, then they need to know about Dig directly, and I think that's OK.

**Comment by abhinav** [comment]
I don't feel strongly about whether we add the alias or not. The original reasoning for the alias was that users of fx don't necessarily know that dig is being used.

**Comment by glibsm** [comment]
I think we decided against this right? This also points people to dig, since understanding that is kins of a requirement anyways if you want "advanced in/out" usage

**Comment by abhinav** [comment]
Sounds good.
