### ISSUE TITLE
Readme is almost completely bare

### ISSUE THREAD

**Issue by glibsm** [uber-go/fx#511]
It was completely removed as part of the modular refactor, need to bring back the relevant content. 

Perhaps a basic example of what things look like is a good starting point.

**Comment by akshayjshah** [comment]
Do we have to keep the markdown-to-GoDoc converter?

I've generally seen successful projects use README.md and GoDoc for different purposes: the README is basically a sales pitch, while the GoDoc is user documentation.

**Comment by glibsm** [comment]
We can try out to see what the life looks like without it, particularly if we're not willing to invest in it to make it better and take it across the finish line. It doesn't work well for all the md cases.

**Comment by akshayjshah** [comment]
Just to cut down on pre-release blockers, maybe start without it and see whether we want to invest more down the road?

**Comment by Lupie** [comment]
+1 to Akshay

**Comment by breerly** [comment]
README is heading in the right direction as of #555 - closing for now.
