### ISSUE TITLE
how you define 1700 micro services ? base on business or code lines ?

### ISSUE THREAD

**Issue by joostshao** [uber-go/fx#515]
cloc ? or business logic ? 

and may be some functions composite to a microservice ?
![a0175ab3-2e9e-4d0f-bd4f-c9f591451955](https://user-images.githubusercontent.com/3615951/27221144-24aa824a-52ba-11e7-8d69-70f50f6b9da3.png)

**Comment by akshayjshah** [comment]
These are separate processes, each with its own codebase, communicating over the network.
