### ISSUE TITLE
Provide: Detect options

### ISSUE THREAD

**Issue by abhinav** [uber-go/fx#553]
It's easy for someone to do,

```
fx.Provide(
  foo,
  bar,
  anotherthing.Module,
)
```

Where,

```
package anotherthing

var Module = fx.Provide(...)
```

In such a case, the user will get a cryptic error like,

```
Failed to start: can't provide fx.optionFunc: unable to collect return types of a constructor: must provide at least one non-error type
```

We should detect if the value being provided is an `fx.Option` and perhaps treat is as such, or at least give a more obvious error message.

**Comment by breerly** [comment]
Let's go with the more clear error message!

**Comment by breerly** [comment]
Might as well do the same thing in `fx.Invoke()` as well.
