### ISSUE TITLE
Error when dig.In struct contains unexported fields

### ISSUE THREAD

**Issue by bayesianmind** [uber-go/fx#565]
It's very easy for users to make one of their params types have unexported fields which means it will silently have the default value.

It seems reasonable to me to to say that a struct being used as a dig.In struct should not be used for anything else. This means that we can warn users if any fields are unexported and improve this silent rough edge users can easily hit.

**Comment by breerly** [comment]
Agreed - I've ran into this several times.

In fact, it seems like every field on an `fx.In` and `fx.Out` should be required to be exported - that would save people from this class of bug entirely.

Should we explore erring if there are any private fields?

**Comment by glibsm** [comment]
> This means that we can warn users

How do we warn someone in the context of only-errors-language? :)

I'm open to returning an error for private types on `dig.In/Out`.

**Comment by bayesianmind** [comment]
Let's just fail in that case then.. I can't think of any good reason to have a mixed use struct

**Comment by breerly** [comment]
After thinking on it, I'm even more convinced that this should produce an error.

We can always, without breaking anything, go from error to no error, but we won't be able to introduce an error post 1.0.

**Comment by bayesianmind** [comment]
Let's make sure we have a way for users to turn this off for a field.
Maybe we can just reuse optional for that:
```
type Group struct {
dig.In

Config       config.Provider
privateField string `optional:"true"` // ignored for the private field check
```

**Comment by breerly** [comment]
I would rather start without a way to configure - we can always add it later, and like to explore the customer's specific usecase before doing so.

**Comment by bayesianmind** [comment]
I just came up with one, which is why I say this.
In Catalyst handlers we tie user's handlers onto a Group struct which is a dig.In so it gets injected. Users may want to do their own setup stuff directly onto that struct.
They could register a provide and a custom type but it's more overhead to do it that way, and I don't want to limit users without a good reason.
I'll ping you a direct link to the code in question as it's not OSS.

**Comment by alsamylkin** [comment]
It is much better to skip the private fields for exactly that reason, e.g. json.Unmarshaller behaves like that.

**Comment by abhinav** [comment]
I would rather skip private fields than disallow them. I can easily see people using `dig.In` types for logic that happens to rely on private fields.

If we disallow private fields, I strongly disagree with using the `optional` tag to opt fields out of the check. Either we allow private fields or we don't. I don't want to add more and more logic to tags.

**Comment by breerly** [comment]
Since dig.In and dig.Out structs are not general purpose, I think erring would help the end-user the most because they won't have the confusing experience Ben and I have gone through.

There's no reason to put private fields on these structs as far as I can tell - if that is need then the struct should be composed into another shape that does have private fields.

**Comment by bayesianmind** [comment]
Give me a day to code up what this would look like for Catalyst handlers and see if it seems ok.. I think this is a big usability win in general as it's an easy error to make

**Comment by bayesianmind** [comment]
It looks good for Catalyst, so I'm on board with erroring in this case.
We can always make it less strict / provide an opt-out in the future while preserving compatibility.

**Comment by breerly** [comment]
Thanks Ben!

**Comment by glibsm** [comment]
Quick clarification. The issue title says `fields available in graph`.

Is it only fields available in the graph, or should we do it for all private fields? I think it's all private fields on sentinels that should get this warning.

**Comment by abhinav** [comment]
All private fields is more predictable. Let's go for that.

**Comment by bayesianmind** [comment]
Makes sense I'm on board

**Comment by glibsm** [comment]
Moving this issue to dig, seems like it was filed against the wrong repo.
