### ISSUE TITLE
Create functions to facilitate fx.Hook creation

### ISSUE THREAD

**Issue by glibsm** [uber-go/fx#574]
## Problem

It's pretty annoying to create a `fx.Hook` right now - need to create a struct and populate it's fields, yada yada.

Also, it means that we're tightly coupled to this structure forever and there is very little wiggle room.

Lets take an example from our GoDocs:

```go
lc.Append(fx.Hook{
    OnStart: func(context.Context) error {
        logger.Print("Starting HTTP server.")
        go server.ListenAndServe()
        return nil
    },
    OnStop: func(ctx context.Context) error {
        logger.Print("Stopping HTTP server.")
        return server.Shutdown(ctx)
    },
})
```

## Proposal

It should be a smoother sailing experience if we came up with something `fx.Option`-like for the hooks, as opposed to being so rigid with the structs.

TODO: Example inc.

**Comment by breerly** [comment]
I actually find the proposal more jumbled than the current experience.

As it stands, you attach a single struct to lifecycle.Append, of which you populate one of OnStart or OnStop, or both.

It's a bit beefy when you provide both the OnStart and the OnStop, but I don't really see the issue TBH.

**Comment by breerly** [comment]
@glibsm can you provide some snippets showing the proposed API from the end-users POV? That would be more helpful than seeing the APIs themself.

**Comment by glibsm** [comment]
@breerly Sure.

Let me edit this issue fully showing the vision to hide `fx.Hook` and provide some examples. Right now it's in a weird state of illustrating a backwards compatible change.

**Comment by glibsm** [comment]
Apart from ergonomics of the whole thing, which I still think can benefit from the fx.Options-like interface (and am failing to express), the main reason `fx.Hook` exists as a struct with `Lifecycle.Append` method is because in the initial version of `Lifecycle.OnStart` and `Lifecycle.OnStop` there was no way or correlating the two of them together for reverse ordering, and for stopping when one of the hooks fails.

Consider the following scenario:

```go
func Module(a A, b B, lc fx.Lifecycle) (C) {
    // do stuff
    c := C{}
    lc.Append(fx.Hook{OnStop:func...})
    lc.Append(fx.Hook{OnStart:func...})
    return c
}
```

That's a territory where the behavior gets really weird, and there is nothing that we do to stop it from happening, apart from suggesting only a single call to Append.

**Comment by glibsm** [comment]
What I originally envisioned from the user's perspective is something like this:

```go
lc.On(
	fx.Start(func(context.Context) error {
		// start something
		return nil
	}),
	fx.Stop(func(context.Context) error {
		// stop something),
		return nil
	}),
)
```

The ergonomics of which are a little better, but still suffer from the same problem mentioned above: multiple calls to `lc.On` suffer from ordering problems.

Alternatively, we could try to return the end user to something that we originally started with:

```
type A struct{}

func NewModule(lc fx.Lifecycle) A {
	a := A{}

	lc.OnStart(func(ctx context.Context) error {
		// do the things
		return nil
	})
	lc.OnStop(func(ctx context.Context) error {
		// do the things
		return nil
	})

	return a
}
```

Correlating start/stop could be done via the stack frame (we already collect the caller for logging purposes).

**Comment by breerly** [comment]
The first example you show uses `fx.Start()` and `fx.Stop()` - how would that work without introducing global state? I'm obv not going to budge on that one :)

Let me think more on the second example, `lc.OnStart()` and `lc.OnStop()` - at first glance I do think users will find that easier than punching out fields in `fx.Hook` struct...

**Comment by breerly** [comment]
@glibsm how exactly does the stack frame help us correlate?

The current implementation collects `OnStart` and `OnStop` hooks in *pairs*. AFAICT, the `lc.OnStart()` and `lc.OnStop()` api would have no way of knowing exactly which hooks belong in which pairs. I think this will be exasperated by the fact that these functions can be called programmatically. 

While I actually buy the ergonomics part of your proposal now, I'm worried that the stack frame correlation would be fragile at best... and am not actually convinced it would even work.

If you want this proposal to go forward, then you're probably going to need to lead with a PR which exercises the stack frame correlation pretty exhaustively.

**Comment by glibsm** [comment]
@breerly `fx.Start` and `fx.Stop` are not going to be global state in the same way that `fx.Provide` and `fx.Invoke` are not global states - they are an implementation of the Options pattern.

Yes I'm aware that if I wanted to push this through I'd need to drive a PR and quick. However, I'm not fully committed to this idea yet - I'm just exploring the options.

I do think that multiple `Append` calls in a constructor is a problem.

**Comment by akshayjshah** [comment]
`Lifecycle` is an interface, which is how we've provided unit testability. Adding methods to interfaces is a breaking change. Converting the `Hook` struct into `OnStart` and `OnStop` methods prevents the introduction of any other lifecycle concepts in the `1.x` release series, which is how we ended up with the current design.

**Comment by glibsm** [comment]
I'm going to abandon this issue for now after talking at length with @abhinav. It's a part of the code that hasn't been touched for a long time and touching it a few days before release is too much risk. It's been rock solid, therefore should make it into the release.

If we come up with a new way to do lifecycle management, we can implement it in a purely additive way and signal a deprecation of `Lifecycle.Append` through godocs.
