### ISSUE TITLE
Don't leak dig errors

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#576]
We should make sure that Fx is wrapping all errors that come out of public APIs with Fx errors.

This will make more sense to end users, since they'll be seeing Fx errors instead of Dig in some cases. When we document these cases from Fx's docs, I want to be sure I'm talking about Fx errors and that we have a point of control in the primary library.

Thoughts?

**Comment by breerly** [comment]
Ps I would attach this to the v1.0.0 milestone but it looks like mobile site doesn't support this.

**Comment by breerly** [comment]
To be more concrete, I'm suggesting all errors that come out of fx.App.Start are wrapped with an fx.StartError instead of transparently returning any error encountered in lower layers.

**Comment by breerly** [comment]
Actually, I suppose it means fx.App.Err() doesn't leak any non-Fx error types...

**Comment by abhinav** [comment]
Wrapping all errors is undesirable behavior. If my constructor fails, I _want_
that error to be returned as-is.

Plus, the word leaking implies that you're violating API boundaries at some
point. These errors don't have any API attached to them; they're just plain
`error` objects. Wrapping makes sense only if they are not informative enough
or if they have special behavior attached to them which you want to be
interpreted differently at the higher layer. For example, converting a socket
error to a handshake error.

**Comment by breerly** [comment]
I can buy that! Let's roll this way and see how it goes :)

**Comment by akshayjshah** [comment]
Why? None of the public APIs leak anything - they're all `error`, which makes changing the concrete type fully backward-compatible.

Let's discuss, but this doesn't block a 1.0.

**Comment by akshayjshah** [comment]
ABG beat me to it :)

**Comment by breerly** [comment]
I closed the task :)
