### ISSUE TITLE
Please use self-documenting signatures in the Log interface

### ISSUE THREAD

**Issue by yurishkuro** [uber-go/fx#58]
Currently ulog.Log interface is written with methods like this:
```go
Debug(string, ...interface{})
```

* Is the first parameter a format string (like in Printf) or a plain message string?
* Are the arguments interpreted as in Printf or as alternating key-value pairs as in go-kit?

**Comment by yurishkuro** [comment]
@sectioneight fyi

**Comment by sectioneight** [comment]
cc @uber-go/service-framework

**Comment by anuptalwalkar** [comment]
Created Jira GFM-161 to address this issue.
