### ISSUE TITLE
How to fail the application from an OnStart hook

### ISSUE THREAD

**Issue by sagikazarmark** [uber-go/fx#600]
Take the following - highly unlikely - scenario:

```go
func NewMux(lc fx.Lifecycle, logger *log.Logger) *http.ServeMux {
	logger.Print("Executing NewMux.")
	mux := http.NewServeMux()
	server := &http.Server{
		Addr:    ":8080",
		Handler: mux,
	}
	server2 := &http.Server{
		Addr: ":8080",
	}
	// If NewMux is called, we know that someone is using the mux. In that case,
	// start up and shut down an HTTP server with the application.
	lc.Append(fx.Hook{
		OnStart: func(context.Context) error {
			logger.Print("Starting HTTP server.")
			go server.ListenAndServe()
			go server2.ListenAndServe()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			logger.Print("Stopping HTTP server.")
			server.Shutdown(ctx)
			return server2.Shutdown(ctx)
		},
	})

	return mux
}

func Register(mux *http.ServeMux, h http.Handler) {
	mux.Handle("/", h)
	http.Handle("/", http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		fmt.Println("Got another request")
	}))
}
```

(The above code is just copied from the documentation example, the rest is unchanged)

This code sample tries to demonstrate one of the cases when starting the application itself fails (can't listen on an already used port), but we don't know about it because the code starting the server does not block the OnStart hook. We obviously can't write it otherwise.

The problem is in this case the application continues running, like nothing happened. To make things even worse, there is probably no way from the outside to notice the problem, since the port is in use (that's why I picked this example). In other cases a health check may be able to detect that there is something wrong, and restart the application.

(I could have solve the issue with a `net.Listen` call, but the actual example is less important)

This is obviously an edge case, but I probably can't think of any nastier debug scenario than having a running process but a failed server inside.

One possible solution could be providing the application a way to manually fail from the inside. That way a failing server could cause the application itself to stop.

What do you think?

**Comment by lrewega** [comment]
A trivial way to fail is to invoke `panic()`,  but we can do better than that.

For my applications, I dislike the idea of components controlling the app lifecycle directly. Rather, I prefer to provide the integrator (i.e. wherever `app.Start()` is invoked) with the information necessary to make such a decision. More specifically, I strongly dislike the idea of libraries deciding when an application should start or stop -- I think it classifies as surprising behaviour.

A solution I use in one of my applications is to provide an error channel to select on, so that the the app can be stopped if deemed necessary. For example, my `main` function looks something like:

```golang
func main() {
	var g struct {
		Logger           *zap.SugaredLogger
		SomethingErrChan <-chan error `name:"SomethingServeError"`
	}

	app := fx.New(
		...
		fx.Provide(NewSomething),
		...
		fx.Extract(&g),
	)

	...
	if err := app.Start(...); err != nil {
		...
	}

	select {
	case signal := <-app.Done():
		g.Logger.Infof("Received signal: %v", signal)
	case err := <-g.SomethingErrChan:
		g.Logger.Errorf("Something server stopped unexpectedly: %v", err)
	}

	...
	if err := app.Stop(...); err != nil {
		...
	}
}
```

and then my module might look like:

```golang
type Result struct {
	fx.Out

	SomethingErrChan <-chan error `name:"SomethingServeError"`
}

func NewSomething(lifecycle fx.Lifecycle) (Result, error) {
	...
	errc := make(chan error, 1)
	lifecycle.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			go func() {
				defer close(errc)
				if err := srv.ListenAndServe(); err != nil {
					errc <- err
				}
			}()

			select {
			case err := <-errc:
				return err
			default:
			}
			return nil
		},
	})

	return Result{
		SomethingErrChan: errc,
	}, nil
}
```

That being said, this is kind of ugly, and it would be nice to have a standardized approach.

(Also, I've found it useful when authouring servers to just have `ListenAndServe()` return `<-chan error` as it makes this sort of thing far less painful.)

**Comment by sagikazarmark** [comment]
Thanks for your detailed answer. That's actually a great idea, thanks for that as well.

I ended up with the following solution for now:

```go
type ErrChan chan error

func NewErrChan() ErrChan {
	return make(ErrChan, 1)
}
```

This creates a constructor for a named type (so I don't have to create an Out struct) and it works globally for multiple servers as well. When one of the servers fail, it causes the application to fail.

Another thing I did was this:

```go
	params.Lifecycle.Append(fxt.Hook{
		OnStart: func(ctx context.Context) error {
			lis, err := net.Listen("tcp", ":8080")
			if err != nil {
				return err
			}

			go func() {
				params.ErrChan <- server.Serve(lis)
			}()

			return nil
		},
		OnStop: func(ctx context.Context) error {
			return server.Shutdown(ctx)
		},
	})
```

I listen on the interface manually, so the application fails early if it does not succeed.

What do you think?

I would say this is a solution for now, but I would also be happier with a standardized error handling approach.

**Comment by lrewega** [comment]
@sagikazarmark that certainly works, but I have a few problems with it:

- Your provided Fx options now require `ErrChan` as an input, meaning either consumers who might not care about it must provide it, or perhaps you bundle it as provided in a top level `Module` variable. I like returning a result as it can easily be ignored if it is not important.
- There is no way to peel apart errors from different modules -- it would be difficult to stop if only certain servers error.
- There is no clear directionality with the provided error chan. It's not clear who should read or write to the channel.

Ultimately it's of course up to you -- if you're not exporting anything to be consumed elsewhere, it's certainly not a big deal. I would be concerned about recommending this as a standard approach.

**Comment by sagikazarmark** [comment]
Good points, certainly things to consider when thinking about the standard, but in my case I don't have reusable modules, only the main application and I don't want to maintain separate error channels if the resolution is the same.

**Comment by sagikazarmark** [comment]
After giving more thoughts to the problem, I decided to return the err channel as you suggested:

- less coupling to a "global" something in my code
- more fine grained error handling

**Comment by sagikazarmark** [comment]
I believe this issue can be closed. The original question has been answered, a good number of examples were provided and I tried the solution out, worked well for me.

Opening a followup issue for standardized error management could probably be a good idea.
