### ISSUE TITLE
Injecting Named Values without rewriting construtors

### ISSUE THREAD

**Issue by abhinav** [uber-go/fx#610]
Based on offline discussions, we want to support the ability to inject a named
value into an Fx application without rewriting or wrapping an existing
constructor to return an `fx.Out` struct.

Specifically, given the constructor,

```go
func NewThing(...) (*Thing, error)
```

We want users to be able to `fx.Provide` a `*Thing` with the name "foo"
without having to write the following.

```go
type thingResult struct {
    fx.Out
    
    Thing *Thing `name:"foo"`
}

func newThing(...) (thingResult, error) {
    thing, err := NewThing(...)
    return thingResult{Thing: thing}, err
}
```

Implementing support for this will become significantly easier once uber-go/dig#175
lands but we still need to decide on the user-facing API for this.

Based on an offline discussion with @prashantv, these are the options we are
considering for the Fx-level API for this functionality.

-   ### `fx.Annotated` struct

    Users will `fx.Provide` this struct instead of their constructor.

    ```go
    fx.Provide(
        ...,
        fx.Annotated{
            Name: "foo",
            Fn: NewThing,
        },
    ),
    ```

    **Pros:**

    -   Idiomatic in Go
    -   Easy to add new options like `Group: "foo"`

    **Cons:**

    -   If we ever decide to support providing things besides constructors,
        we're stuck with the name `Fn`.

-   ### Builder Pattern
 
    Users will call `fx.Annotate` on a constructor and receive an opaque
    `fx.Annotated` object which they can call `Name` on.

    ```go
    fx.Provide(
        ...,
        fx.Annotate(fn).Name("foo"),
    )
    ```

    **Pros:**

    -   Easy to add new options: `fx.Annotate(fn).Name("foo").Group("bar")`
    -   No naming commitments for things that can be `Provide`d

    **Cons:**

    -   Builder Pattern is non-standard in Go: we don't know of any production
        APIs from the Go team that use the Builder Pattern

-   ### Decorator Functions

    Users will call `fx.Named`, providing a name and a constructor.

    ```go
    fx.Provide(
        ...,
        fx.Named("foo", fn),
    )
    ```

    **Pros:**

    -   Idiomatic in Go
    -   No naming commitments for things that can be `Provide`d

    **Cons:**

    -   Namespace pollution: adding a Group option requires taking up
        `fx.Grouped`
    -   Chaining options is annoying: `fx.Grouped("foo", fx.Named("bar", fn))`

CC @bayesianmind @uber-go/fx

**Comment by bayesianmind** [comment]
I think any of these options would work, though I'm most in favor of the builder pattern because FX doesn't currently have any 'struct' apis. Despite builder not being that common in Go it's a very nice pattern with a lot of great properties.
One other thing to consider is that a natural next step after this would also be to support named `fx.Populate()` to eliminate the forced fx.In struct to use named inputs. Thinking about options for that API may inform this choice as well.

**Comment by prashantv** [comment]
> I think any of these options would work, though I'm most in favor of the builder pattern because FX doesn't currently have any struct apis. Despite builder not being that common in Go it's a very nice pattern with a lot of great properties.

I'm not against the builder pattern, but I'd prefer to keep our APIs idiomatic to Go.

> One other thing to consider is that a natural next step after this would also be to support named fx.Populate() to eliminate the forced fx.In struct to use named inputs. Thinking about options for that API may inform this choice as well.

Thinking about supporting this in `Populate` is a good idea, it would be great if the same function/struct could be used on that side.

> If we ever decide to support providing things besides constructors, we're stuck with the name Fn.

We could keep the field name itself generic, especially if we want it to work with `Populate`,

```go
fx.Provide(
  fx.Annotated{Name: "foo", Target: fn},
)

fx.Populate(fx.Annotated{Name: "foo", Target: &v})
```

**Comment by bayesianmind** [comment]
Where are we on this? We'd love to steer our customers towards this.

**Comment by breerly** [comment]
@Ben - is this something your hoping will make it into a certain upcoming 1.0?

**Comment by abhinav** [comment]
The required dig change has been merged. I haven't had a chance to touch the Fx side yet.

**Comment by bayesianmind** [comment]
Yeah I want to get rid of our usage of yarpc.InjectClients()
We don't want to hold 1.0 for that though. I think once this is available it'll just be a template change.

**Comment by breerly** [comment]
@bayesianmind agreed; in fact, I see us deprecating `yarpc.InjectClients` in a future 1.x release.

**Comment by dimiro1** [comment]
Hello all, I just found this library and found it amazing. I was wondering if someone from Uber is working to implement one of the approaches discussed here.

Thanks

**Comment by abhinav** [comment]
Thanks @dimiro1! Yes, we agreed on the `fx.Annotated`-struct based approach
and plan to implement it. That said, nobody is actively working on this right
now. We hope to have someone work on this in the next couple weeks.  Meanwhile
if you'd like to take a stab at it, we welcome PRs. :)

**Comment by dimiro1** [comment]
Hello @abhinav, I implemented a first version of the implementation, I would like to receive feedback.

https://github.com/uber-go/fx/pull/633

**Comment by glibsm** [comment]
Just to close thing out (before github auto-closes this issue on merge), we're close to merging a PR which will implement the first option (annotated struct).

It seemed like the most balanced and futureproof approach which leaves some room for things like groups, or any other stuff we can dream up.
