### ISSUE TITLE
internal: Structured Fx options

### ISSUE THREAD

**Issue by abhinav** [uber-go/fx#621]
Currently, `fx.Option` are opaque function pointers. This leaves very little
room for introspection and it results in bad error messages for cases where
the same `fx.Option` was provided multiple times.

We should store options with more internal structure. I'm suggesting something
similar to,

```go
package internal

type Option interface{ ... }

type ProvideOption struct {
    Funcs []interface{}
}

type InvokeOption struct {
    Funcs []interface{}
}

type ChainOption struct {
    Options []Option
}
```

`fx.Provide`, etc. would still return an opaque `fx.Option` object but
internally it would be more structured. These won't be interpreted as
`dig.Container` operations *until* `fx.New` is called.

This would make a few things possible:

- Every fx.Provide, fx.Invoke, and fx.Options call can record a stack trace of
  where it was called into the internal structure. When a failure occurs
  because say, two types were provided from two different modules, the stack
  traces will help find exactly where the conflicting 
  
  To elaborate on that a bit, today if you do,
  
    ```go
    fx.New(
        foo.Module,
        bar.Module,
    )
    ```

  And they both happen to be including `baz.Module`, the error you will see
  will be specific to the types provided by `baz.Module`: "type whatever
  already in the container".  If the `fx.Options` calls for `foo.Module` and
  `bar.Module` recorded where they were called, the error message could say
  that one instance is coming from foo and one from bar.

- `fx.Option`s could become printable, to show the effect they will have on
  the container without actually doing it.
  
- We could include an `fx.Scope(name string, fx.Option)` API (better name
  TBD), which would allow replacing named fx.Options with something else for
  tests. This would address the recurring ask we have of being able to replace
  Fx modules for tests.

I'm sure there are other features this makes possible that I haven't
thought of yet.

**Comment by breerly** [comment]
cc @willhug

**Comment by breerly** [comment]
> We could include an fx.Scope(name string, fx.Option) API (better name
TBD), which would allow replacing named fx.Options with something else for
tests. This would address the recurring ask we have of being able to replace
Fx modules for tests.

I'm trying to understand this better - can you jot down some end-user code using `fx.Scope`?

**Comment by abhinav** [comment]
> > We could include an fx.Scope(name string, fx.Option) API (better name
TBD), which would allow replacing named fx.Options with something else for
tests. This would address the recurring ask we have of being able to replace
Fx modules for tests.
>
> I'm trying to understand this better - can you jot down some end-user code
using `fx.Scope`?

This is very theoretical at this point in that I haven't thought the APIs
through fully. The idea is that we would encourage (but not require) module
authors to specify a name for their modules with fx.Scoped.

    // foo/module.go
    
    package foo
    
    var Module = fx.Scoped("foo", fx.Options(...))
    
    // bar/module.go
    
    package bar
    
    var Module = fx.Scoped("bar", fx.Options(..., foo.Module))
    // Note that bar includes foo
    
Then users would be able to replace named subsections of the fx.Option tree
with their own variants. Theoretically, this would be provided for tests only
via `fxtest.ReplaceScope(name string, opt fx.Option)`.

    fxtest.New(
        bar.Module,
        fxtest.ReplaceScope("foo", myTestFoo),
    )

**Comment by breerly** [comment]
> users would be able to replace named subsections of the fx.Option tree
with their own variants. Theoretically, this would be provided for tests only
via fxtest.ReplaceScope(name string, opt fx.Option).

I see, so it's not that *anything* can be replaced at will, but instead that you can specify explicitly that a given module can be replaced. For example, you might specify in the UberFX stack that the logging module can be replaced, with the idea that we might replace it in cloud with Stack driver.

Suggest `fx.Replaceable` and `fx.Replace` - scope is a vastly overused term.

**Comment by breerly** [comment]
Onboard w/ this issue: it opens doors to some higher-level features we couldn't get easily otherwise, and is transparent to the user because it's an internal change.

I suggest that we make this change as a way to implement one of these features (`fx.Replaceable`?), instead of implementing it in anticipation of these coming later.

**Comment by abhinav** [comment]
@glibsm Not quite.

First, just to clarify: What I'm proposing in this issue is not that feature.
I'm proposing some internal refactoring that cleans up some implementation
details and makes richer feature possible in the future.

As for the `fx.Scope/fxtest.Replace` idea: If we were to implement that, the
sell is that fx.Scope lets you annotate a group of options with a name; this
could be used for introspection, better error messages, etc. Further,
`fxtest.ReplaceScope` would let you replace a *named* set of options (or
"fx.Module"?) in *tests only*. This explicitly does not deal in types or
constructors, requiring instead that a replaceable chunk of options be given
an explicit name.

Again, this issue is just proposing some refactoring. `fx.Scoped` is just an
example of what is otherwise difficult to implement. If we want to discuss
that feature, I would prefer we do that in a separate issue.

**Comment by abhinav** [comment]
We have this today to some degree. 

https://github.com/uber-go/fx/blob/5bb91324257a9b2222ba7ecc21017fab738b67be/app.go#L95

Closing
