### ISSUE TITLE
Stop using glide

### ISSUE THREAD

**Issue by y0ssar1an** [uber-go/fx#631]
It's a deprecated package manager.

**Comment by akshayjshah** [comment]
Our internal ecosystem of a few thousand Go projects is *entirely* Glide-based, so (for now) we need a `glide.yaml` manifest here.

We're planning to wait until Go 1.11 is released before doing our next round of comparison between dep and Go modules. I'd really prefer not to maintain all three metadata files in parallel.

**Comment by jdharms** [comment]
Has there been any update here?

**Comment by robbertvanginkel** [comment]
Closed with #685.
