### ISSUE TITLE
Even if NopLogger is provided DI failures should produce a report.

### ISSUE THREAD

**Issue by hsyed** [uber-go/fx#634]
Once past development in a lot of scenarios you would bind a `NopLogger` by default. 

An instance of this when fx is used to wire up sub-components. You don't want logging noise in those cases.

Not having this behaviour hurts quick development cycles and if you push something broken accidentally.... 

This is what you get for a wiring error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12de726]

goroutine 1 [running]:
github.com/hsyed/crawler/crawl.(*Task).Done(0xc420110da0, 0x13ff8c0)
	/Volumes/work/src/github.com/hsyed/crawler/crawl/task.go:67 +0x26
main.main()
	/Volumes/work/src/github.com/hsyed/crawler/main.go:30 +0x27f
```

**Comment by blampe** [comment]
Hi @hsyed, can you give us some example code that demonstrates the behavior you're seeing? And what behavior would you expect to see instead?

**Comment by hsyed** [comment]
@blampe The example error above is what you see when a binding / service is missing from the container and there is a `NopLogger` bound. 

Binding a `NopLogger` should opt out from verbose logging not fatal logging -- in other words fx should log something out when it panics due to missing bindings. 

For example here is the last logging line in a missing binding situation that occurs when a logger is bound, something like this should be printed out to stderr I think.
```
2018/07/27 22:02:29 [Fx] Error during "reflect.makeFuncStub()" invoke: could not build arguments for function "reflect".makeFuncStub (/usr/local/Cellar/go/1.10.3/libexec/src/reflect/asm_amd64.s:12): failed to build *crawl.driver: missing dependencies for function "github.com/hsyed/crawler/internal/crawl".newDriver (/Volumes/work/src/github.com/hsyed/crawler/internal/crawl/driver.go:32): type int is not in the container, did you mean to Provide it?
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by hsyed** [comment]
I didn't know the app had an `Err()` function, this contains an appropriate error that can be used.
