### ISSUE TITLE
Struct tags interpretations  should be order independent

### ISSUE THREAD

**Issue by hsyed** [uber-go/fx#635]
``name:"foo",optional:"true"`` is valid but``optional:"true",name:"foo"`` is not.

in the latter case optional mechanics work but name binding does not.

**Comment by abhinav** [comment]
Hello, @hsyed. Are you able to provide a sample to reproduce this. Our tests
show that this works just fine. I've added an explicit test to the underlying
library (uber-go/dig#204) to verify this case just in case.

(Also, I'm assuming you meant to use spaces to separate the tags, not commas.
Go requires tags to be separated by spaces.)

**Comment by hsyed** [comment]
@abhinav it was the comma causing the problem! 

I assumed the comma was needed since it's used to separate tag options, getting back into go after bit of a hiatus.
