### ISSUE TITLE
Should a provided Logger be useable within fx.Logger() ?

### ISSUE THREAD

**Issue by DavyJ0nes** [uber-go/fx#647]
Firstly thank you for creating this package! It has been super useful in creating easily configured applications by allowing dependencies to be defined at runtime.

This issue is a question/request that I think might be useful for other users. The question is:

> Do we think that it is a good idea to allow `fx.Logger` to use a logger that has been provided, similar to the behaviour of `fx.Invoke`?

### More Info
I have a logger that can be configured from environment variables that I am using within my application. The parsing of the environment variables into configuration settings is also used by other components of the application.

In order to use the same configuration of logger for `fx` and my application I need to instantiate the environment settings twice, both within `fx.Provide` and outside so that I can create `logger` that will be used both as a dependency for `router` and `server` as well as for `fx`. e.g.

```go
func StartApplication() {
	logSettings, err := config.NewLoggerSettings(config.GetEnvironmentSettings)
	logger := config.NewLogger(logSettings)

	fx.New(
		fx.Provide(
                        config.GetEnvironmentSettings,
                        logger,
			config.NewServerSettings,
			router.New,
			server.New,
		),
		fx.Logger(logger),
		fx.Invoke(server.Start),
	).Run()
}
```

Ideally I would like to be able to do something like the following:

```go
func StartApplication() {
	fx.New(
		fx.Provide(
                        config.GetEnvironmentSettings,
                        config.NewLoggerSettings,
                        config.NewLogger,
			config.NewServerSettings,
			router.New,
			server.New,
		),
		fx.Logger(config.NewLogger),
		fx.Invoke(server.Start),
	).Run()
}
```

**Comment by abhinav** [comment]
Hello and thank you! We're glad people found it useful.

This is a valid idea but it presents some difficulties: In many scenarios, and
certainly in our own internal usage of Fx, we need to instantiate some other
modules (environment inspection, configuration loading, etc.) before we can set
up the logger correctly. Much of Fx's logging happens before we
invoke/instantiate anything ("here is everything I know about") followed by the
invokes ("here is what I actually ran and why"), followed by the lifecycle
operations. If acquiring the logger requires an invoke-like operation, we'll be
unable to log anything before that phase.

That said, I think this is a valid problem and we are open to a better solution
to this. Meanwhile, the way you're doing this currently is a reasonable
workaround.

Thanks!

**Comment by DavyJ0nes** [comment]
Thank you for the reply. That's a really good point and one I hadn't considered. Having a lightweight logger for fx and a provided one for the application is a good way of thinking about it.

Will close this off.

Thank you!
