### ISSUE TITLE
possible to use fx to inject mocks?

### ISSUE THREAD

**Issue by rubensayshi** [uber-go/fx#649]
trying to write tests and provide a mock service instead of the real, but I get an "already provided" error, is the only way to do this by making sure the original service is not being provided when I want to provide a mocked version?

**Comment by glibsm** [comment]
It's difficult to say without seeing your particular setup. There is currently no mechanism to override or replace existing objects in the graph (although that has been discussed in the past).

You could set your application in a way to accept a flag to omit certain components that will be added at a later time and add them in tests, or completely re-construct application from scratch in your test.

**Comment by elliotchance** [comment]
Urgh, seriously? Under unit tests it makes perfect sense to supply values for mocked services or other static input. I get that it shouldn't be a feature of the `fx` package, but it should be a feature of the `fxtest` package. Perhaps something like?

```go
app := fxtest.New(t,
    // Provides a *Flag just like fx.Supply. However, will not trigger
    // an error when *Flags is provided later. Ideally, not call the
    // constructor at all.
    fxtest.Supply(&Flags{Service: "foo"}),

    // Normal app options.
    opts(),
)
```

Thinking out loud: If `*Flags` is provided by a constructor that also provides other types, it would be acceptable to just ignore the return value of `*Flags` with the already set value. If this causes issues under test, a person should break up their constructors so `*Flags` is provided independently (and hence won't be called at all).

**Comment by sywhang** [comment]
Hey all, 

It's been a very long time since this request came in, but we finished working on improving fx in the past few months and you can now achieve this in v1.17.0 with the newly added `fx.Module` and `fx.Decorate` APIs.

Specifically, here is how you might go about injecting mocked types:

```
fx.New(
  fx.Provide(
    func() Service {...},
    // ...
  ),  

  fx.Module("test",
    fx.Decorate(func() *Service {
      // returns a mocked *Service
    }),
    fx.Invoke(func() { 
      // will see mocked *Service, only within this Module. 
    }),
  ),
)
```

**Comment by rubensayshi** [comment]
hey @sywhang that's pretty sweet! I'll revisit fx in the next few weeks thanks!
