### ISSUE TITLE
Why are logs written to stderr?

### ISSUE THREAD

**Issue by kfoxb** [uber-go/fx#664]
While going through our logs and filtering them to only errors I was surprised to see a lot of fx initialization messages there that didn't report any errors.

I was wondering what is the rationale of writing everything to stderr as opposed to writing most informational logging to stdout and only errors to stderr?

**Comment by abhinav** [comment]
Fx only logs at startup, not during the regular operation of the application.
At startup, we decided that Fx should default to *some* visibility into what
was available, what was being wired up, etc.

Fx defaults to logging these things to stderr but you can change that by
providing your own [fx.Logger][1]. You can also use the [fx.NopLogger][2]
option to completely silence Fx's startup output.

[1]: https://godoc.org/go.uber.org/fx#Logger
[2]: https://godoc.org/go.uber.org/fx#NopLogger

**Comment by abhinav** [comment]
Closing since this was just a question. Feel free to reopen if you want to
discuss this further.

**Comment by kfoxb** [comment]
Gotcha, thank you for the explanation @abhinav :-)
