### ISSUE TITLE
dig.As

### ISSUE THREAD

**Issue by rssathe** [uber-go/fx#673]
How do I use dig.As with an fx app?

**Comment by glibsm** [comment]
`dig.As` hasn't been released yet, you can see https://github.com/uber-go/dig/pull/235 for why it was halted slightly.

The plan for usage inside fx is through `fx.Annotated` (not implemented yet) that will function similarly to how `fx.Annotated` can do named and grouped params.

**Comment by glibsm** [comment]
Going to leave this issue open to track the `fx.Annotated.As` work.

**Comment by phamtai97** [comment]
Hi @glibsm
I am having the same problem as you, the issues have been resolved yet ?

**Comment by sywhang** [comment]
`fx.As` has been implemented with #795.

**Comment by AFMiziara** [comment]
I was testing this solution with the provided example in the docs, but I am getting error `type io.Writer is not an expression` . Am I missing something?

```go
fx.Provide(
  fx.Annotate(bytes.NewBuffer(...), fx.As(io.Writer))
)
```

**Comment by sywhang** [comment]
@AFMiziara you're missing a `new`. Interface itself is not a valid expression in Go.

```go
fx.Provide(
  fx.Annotate(bytes.NewBuffer([]byte{}), fx.As(new(io.Writer)))
)
```

I see that in the docs we forgot to add the new there. Let me go fix that.
