### ISSUE TITLE
Group support for slice directly

### ISSUE THREAD

**Issue by mschneider82** [uber-go/fx#693]
I want to provide a slice of a group directly, but I cannot get this done. Is this supported?

This would be nice:
```
type Out struct {
	fx.Out
	Handlers []Handler `group:"Httphandler"`
}
```

This currently seems to work only:

```
type Out struct {
	fx.Out
	Handler Handler `group:"Httphandler"`
}
```

In my case i want to register as much handlers as there are configured in the config file.

**Comment by abhinav** [comment]
Hey, no this is currently not supported but there are plans to do so.

First, to address your immediate need, we've done something similar to the
following internally:

```
type In struct {
  fx.In
  
  Handlers      []Handler   `group:"httpHandler"`
  HandlerGroups [][]Handler `group:"httpHandler"`
}
```

This makes it possible for the corresponding `Out` to produce either a
`Handler` or a `[]Handler`.

For future plans, one idea we're considering here is a `flatten:"true"`
annotation on the `In`, stating that `[]Handler`, `[][]Handler`, etc. will all
be flattened into the same `In`.

**Comment by mschneider82** [comment]
Thanks for the quick solution, I will definitely try this out and remove my current workaround (wrapping the invoked function).

The flatten feature would be very useful! I may would include it to `group:"httpHandler,flatten"`

**Comment by abhinav** [comment]
Ah, `group:"name,opt1,...,optN"` sounds better!

**Comment by mschneider82** [comment]
To have this as tag for an fx.Out would be also nice, since this is mostly in my codebase and the fx.In are mostly imported packages. (So no need to add tags to internal packages)
