### ISSUE TITLE
add ordered Invoke support?

### ISSUE THREAD

**Issue by runner-mei** [uber-go/fx#696]
In my app,  I must first run db initsql.   run db initsql by Invoke.   but it isnot first Invoke.

**Comment by abhinav** [comment]
Hello! We specifically planned for the ordering of invokes to be
unspecified. The reason for this is that if ordering matters, that
requirement should be specified in the form of dependencies: If A
depends on B to have started, then A should have a dependency on B.

Also, we do not recommend actually establishing the database connection
inside an Invoke, but in the OnStart hook. Inside an OnStart hook,
you're guaranteed that the dependencies of that hook have already
started.
