### ISSUE TITLE
deadlock issue

### ISSUE THREAD

**Issue by mschneider82** [uber-go/fx#709]
Hi, i am running services with fx for a while. But one service is crashing once a month in a strange behaivour, the go runtime hangs. even simple go func() print/time.sleep loops doesnt work anymore. 

I tried to debug it with dlv and the goroutine number 1 hangs:

```
  Goroutine 1 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x446677)
```

normally it should be something like:

```
Goroutine 1 - User: /go/src/myservice/vendor/go.uber.org/fx/app.go:679 go.uber.org/fx.(*App).run (0x87f839)
```

I think it has something todo with the signal handler.
I can see a few thousand of goroutines hanging in the same state like goroutine1 (even same 0x address):

```
  Goroutine 11713965 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x446677)
  Goroutine 11713966 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x446677)
  Goroutine 11713967 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x446677)
  Goroutine 11713968 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x446677)
  Goroutine 11713969 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x446677)
````

This happens with go 1.14.1, i know this might be an issue for the golang project, but since i use fx and the fx app also hangs, you might have an idea, since i cannot break it down into a reproducable playground snipped.

**Comment by mschneider82** [comment]
shouldnt the `<-chan os.Signal` channel get unsubscripted from Notify after printing?

https://github.com/uber-go/fx/blob/e0658cfef23e3ed18fc9486b9525a36fbfd5a47a/app.go#L713

e.g.
`defer signal.Stop(done)`

**Comment by prashantv** [comment]
For the stuck goroutines, can you get the full back trace for a few of them? `gr <id>` followed by `stack` should print a few more stack frames that can help determine which mutex they are stuck on.

**Comment by mschneider82** [comment]
hi @prashantv  thanks, i will try it when it happens the next time. 
In the last time i just did stack, default is goroutine 1 ?

```
(dlv) stack
0  0x00000000004659b3 in runtime.futex
   at /usr/local/go/src/runtime/sys_linux_amd64.s:568
1  0x000000000042fd86 in runtime.futexsleep
   at /usr/local/go/src/runtime/os_linux.go:45
2  0x000000000040ad5f in runtime.notesleep
   at /usr/local/go/src/runtime/lock_futex.go:151
3  0x000000000043a238 in runtime.stoplockedm
   at /usr/local/go/src/runtime/proc.go:1977
4  0x000000000043bea6 in runtime.schedule
   at /usr/local/go/src/runtime/proc.go:2460
5  0x000000000043c27d in runtime.park_m
   at /usr/local/go/src/runtime/proc.go:2696
6  0x000000000046188b in runtime.mcall
   at /usr/local/go/src/runtime/asm_amd64.s:318
```

**Comment by mschneider82** [comment]
I will close this, this seems to be caused by a race condition. thanks
