### ISSUE TITLE
fx.Supply with interface types

### ISSUE THREAD

**Issue by oakad** [uber-go/fx#714]
Related to #673 

Let's say we have a following, pretty usual use case:
```
v := some.NewCustomIface()
//
//
//
fx.New(
  fx.Supply(v),
)
```
The type of the value `Supply` actually supplies is not the interface type of `v`, but rather its underlying type, possibly outright private in package`some`. This is pretty unfortunate and limits the use of `Supply` option greatly.

**Comment by ChristopherCastro** [comment]
Im having the same problem, is there any known solution or workaround to this?

**Comment by oakad** [comment]
fx.Provide with appropriate constructor function clearly works.

This may be a limitation of Go language.

**Comment by abhinav** [comment]
Hey there!
You can't provide fx.Supply with an interface type today because fx.Supply will use the most specific type available.
However, in #714 and #802, we're adding a new feature that will help here.
With the new feature you should be able to do:

```
fx.Supply(
  fx.Annotate(v, fx.As(new(SomeCustomIface))),
)
```
