### ISSUE TITLE
Feature request: easy constructor wrapper for named/grouped values

### ISSUE THREAD

**Issue by oakad** [uber-go/fx#715]
`fx.Annotated` makes it easy to produce named and grouped values. But on the consumer side things are less pretty.

Let's say we have a constructor with many parameters and we want to make some of them named/grouped. Right now, the only option to address this is by creating a wrapper function taking an `fx.In` derived parameter resulting in a rather long winded and untidy boilerplate code with some one off struct types on top.

It may be possible to come with a constructor wrapper accepting a hint of some sort in addition to the constructor; possibly as simple as a specially coded string:

```
fx.New(
  fx.Provide(
    fx.WithNames(", , funnyName,", myCons),
  ),
)
```

The implied meaning being that third argument of `myCons` must come from a provider annotated with name "funnyName"

.

**Comment by abhinav** [comment]
Hey there! This was added in #757. You should be able to do:

```go
fx.Provide(
  fx.Annotate(myCons, fx.ParamTags("", "", `name:"funnyName"`)),
)
```

We haven't released it yet—we're hoping to do that right after we finish work on #795.
Stay tuned!

Closing the ticket pending release of the feature.
