### ISSUE TITLE
how to update registered provides ?

### ISSUE THREAD

**Issue by Sefeng** [uber-go/fx#719]
In my app, most providers registerd depend on nacos config,  once nacos config changes , how to update the registered providers gracefully?

**Comment by atul161** [comment]
Any soloution

**Comment by wenerme** [comment]
Reconstruct a context with new config, use context as di container, use fx.App to build the context.

**Comment by abhinav** [comment]
Hi there!
@wenerme's comment is accurate.
Fx does not provide any means of dynamic configuration,
or re-initializing your application when the configuration changes.

Closing because answered.
If I've misunderstood the question, feel free to open a new issue with more details.
