### ISSUE TITLE
Initiating [Learning fx]

### ISSUE THREAD

**Issue by PatrickGTR** [uber-go/fx#731]
Hello, I've tried looking into projects that uses uber-fx and seen the documentation but I just can't get my head around it. If someone can kindly explain how I could access the database connection instantiation so I could ``ping`` or ``query`` onto the mysql server The code below I've provided of what I have achieved so far while learning the framework.

The router work fine. I could not query or ping to mysql as I receive ``2021/03/12 12:51:41 http: panic serving [::1]:64712: runtime error: invalid memory address or nil pointer dereference`` so it seems like the connection handle is invalid.
 
 Thank you!

```go
func main() {

	if os.Getenv("ENV") != "PROD" {
		err := godotenv.Load(".env")
		if err != nil {
			log.Fatal("Error loading .env file")
		}
		fmt.Println(".env file loaded")
	}

	fx.New(
		fx.Options(
			fx.Provide(connectToMySQL),
			fx.Invoke(InitServer),
		),
	).Run()

}

func connectToMySQL(lc fx.Lifecycle) (db *sql.DB, err error) {
	username := os.Getenv("MYSQL_USERNAME")
	password := os.Getenv("MYSQL_PASSWORD")
	database := os.Getenv("MYSQL_DATABASE")
	server := os.Getenv("MYSQL_SERVER")

	lc.Append(
		fx.Hook{
			OnStart: func(ctx context.Context) error {
				db, err = sql.Open("mysql", username+":"+password+"@tcp("+server+")/"+database+"")
				if err != nil {
					panic(err.Error())
				}
				fmt.Println("Successfully connected to mysql server ->", server, "| db ->", database)
				return nil
			},
			OnStop: func(ctx context.Context) error {
				db.Close()
				return nil
			},
		},
	)
	return db, err

}

func InitServer(lc fx.Lifecycle, db *sql.DB) {
	router := chi.NewRouter()

	server := &http.Server{
		Addr:    ":8000",
		Handler: router,
	}

	router.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		err := db.Ping()
		if err != nil {
			fmt.Println("no ping back from mysql server")
			return
		}

		render.Status(r, http.StatusOK)
		render.JSON(w, r, err)
	})

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			go setupServer(server)
			return nil
		},
		OnStop: func(ctx context.Context) error {
			server.Shutdown(ctx)
			return nil
		},
	})
}```

**Comment by twilly** [comment]
There's two phases to running a Fx process: startup and onstart. Typical constructors return valid types at startup and then make connections/do neat things following onstart. E.g. Create and consume HTTP handlers on startup, run ListenAndServe onstart.

Your example breaks because *sql.DB is created in the onstart callback, meaning you've returned a nil *sql.DB in your Fx container. A small twist fixes your situation: return a type that creates database connections. A *sql.DB factory, if you will. InitServer would look something like this:

```go
type storage struct {
	username, password, database, server string
}

func (s *storage) Open() *sql.DB { // ... }

func InitServer(lc fx.Lifecycle, store *storage){
	db, err := store.Open()
	if err != nil {
		return err;
	}
	// ...
 }
```

As an aside, consider delaying network calls during startup or onstart. Requiring a reliable network to start a program tends to be a flaky program. :)

**Comment by PatrickGTR** [comment]
@twilly appreciate your reply! That gave me a heads up why it was returning an invalid connection handle.

regarding the network calls during start up, it was just to test the connection handle as I was having issue with it, I don't plan or have any network calls on start up or during start up.
