### ISSUE TITLE
Scope DI Support?

### ISSUE THREAD

**Issue by fnolla** [uber-go/fx#743]
Hi,

I am wondering if there is any way to have scope dependency injection. For example if I had a db context that had staged data prior to write I would not want that to be a singleton as then multiple requests could cause an issue. If we had scope injection option though then it could be per request. Figured adding this for context would be useful as how .net core does it. https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scoped

**Comment by crclz** [comment]
You can implement lifetime scopes by using multi level container. For example, firstly I create a `singletonContainer` and registered a `idGenerator`. Then I create a `scopedContainer`, and delegate the creation of `idGenerator` to `singletonContainer` by registering the factory method for that goes to `scopedContainer` to resolve the `idGenerator`.

`singletonContainer` is created once per process. `scopedContainer` is created per request. For example, in gin framework, you can create a middleware that create a `scopedContainer` and attach it to gin.Context.keys["some-key"]
