### ISSUE TITLE
Shutdowner: provide option to communicate an exit code or even a value for fx.Run to return

### ISSUE THREAD

**Issue by oakad** [uber-go/fx#763]
`Shutdowner` is a useful mechanism for willfully exiting applications, but it can be even better. To this end, the application channel can be upgraded to carry a value of type

```
type SignalWithValue struct {
    Signal os.Signal
    ExitValue interface{}
}
```
The exit value can then be recovered from the `App.Done` channel value or from `App.Run` return value.

This is mostly useful to set the application exit code to some value, but in a slightly more generic way than simply returning int.

For a bit of context: Dotnet Core allows applications to set the eventual application exit code without actually exiting. This enables a pattern of the following sort:

```
System.Environment.ExitCode = 0;
// do things
// bad things happen
System.Environment.ExitCode = 255;
// Perform an orderly shutdown
(IHostApplicationLifetime).StopApplication();
```

Thus, Dotnet Core can avoid passing any values to `StopApplication`, but we don't have such a luxury in Go.

**Comment by abhinav** [comment]
This is a reasonable feature request,
although I'd like for us to do it slightly differently.

We intentionally left room in the Shutdowner API for functional options.
We can add a new functional option to specify the shutdown exit code:

```
func ShutdownCode(exitCode int) ShutdownOption
```

If unspecified, we'll continue to default to zero.
With this option, users will be able to control the app.Run exit code.

To control the exit code for applications that do not use app.Run,
we'll likely have to offer a replacement for app.Done that returns a different kind of channel,
with a struct type similar to yours.

```
// name TBD
type Shutdown struct {
  Signal os.Signal
  ExitCode int
}
```

Usage:

```
app.Start(...)

ch := app.Something() // name TBD
result := <-ch

app.Stop(...)

os.Exit(result.ExitCode)
```

Internal issue ref: GO-981

**Comment by oakad** [comment]
Should work.

Though, I still think an interface or a particular subtype of `error` (something with `GetErrorCode` in it) there may add a bit of genericity to the feature.

**Comment by jmmills** [comment]
@sywhang This issue should be closed
