### ISSUE TITLE
Is it possible to fx.Supply a context.Context?

### ISSUE THREAD

**Issue by blank-teer** [uber-go/fx#769]
```
func main() {
    ctx := context.Background()
    
    fx.New(
    fx.Supply(ctx),
    fx.Invoke(
	    func(context.Context) {},
    ),
    ).Run()
}
```

i get the following output:

`missing type: context.Context (did you mean *context.emptyCtx?)`

**Comment by abhinav** [comment]
@blank-teer you've closed the issue, so I'm guessing you were able to find the
answer. But in case anyone else stumbles into this issue:

If you use `fx.Supply`, you're letting reflection choose its provided type,
which means it will result in the *most specific* version of that type.

For example, if you do,

    var r io.Reader = &bytes.Buffer{}
    fx.New(
        fx.Supply(r),
    )

Fx will use the most specific type (`*bytes.Buffer`) in the container.

We will resolve this in a future version (see #673, #714) by providing a means
of specifying the type of the value provided to `fx.Supply` explicitly.

Meanwhile, the only way to make it use a more general type is with a
constructor like so:

    var r io.Reader = &bytes.Buffer{}
    fx.New(
        fx.Provide() io.Reader { return r },
    )

Hope this helps.
