### ISSUE TITLE
[Question] Why `Invoked` events are logged as error by `ZapLogger`?

### ISSUE THREAD

**Issue by PonzaMatteo** [uber-go/fx#770]
Hello, I am using the version `1.14.0` and I noticed that `Invoked` events are logged with error level by the `ZapLogger` even when the event does not carry an error.

https://github.com/uber-go/fx/blob/2f6e9690bc6e231a68c39ca88f8b6c90be62af86/fxevent/zap.go#L93-L101 

Is there any specific reason for it or should it be at level Info in case of no error?

**Comment by abhinav** [comment]
Hi @PonzaMatteo, thanks for catching this. You're correct, this is a bug. It should use `Info` if `e.Err == nil`.
We'll fix this shortly.

**Comment by sywhang** [comment]
Thanks for bringing this to our attention @PonzaMatteo. v1.14.1 was released with a fix for this.

**Comment by PonzaMatteo** [comment]
Great!! Thank you for the super prompt response! 🎉
