### ISSUE TITLE
app.Run doesn't log when startup times out

### ISSUE THREAD

**Issue by wdullaer** [uber-go/fx#782]
Due to the usage of `withTimeout`, `app.Run` doesn't log an error when the start timeout expires.

The handling of the timeout is handled outside of the `app.start` function here:
https://github.com/uber-go/fx/blob/9b7de2d2224837121de68b61b5d4ed0d1fd7bf97/app.go#L951
The `err` value is then checked here:
https://github.com/uber-go/fx/blob/9b7de2d2224837121de68b61b5d4ed0d1fd7bf97/app.go#L886
And so the program will just exit with status code 1 and not give any indication that a timeout expired.

You could either create a Timeout event in fxevent, and log that there.
Otherwise you'd have to forego the `withTimeout` function and handle it inside of functions like `app.start` and `app.stop` so the `defer` statement in those can take care of logging.

**Comment by abhinav** [comment]
Thanks for reporting @wdullaer. Yeah, this is a valid issue. We'll fix it.

(Ref internal issue: GO-866)
