### ISSUE TITLE
OnStart hooks not being called

### ISSUE THREAD

**Issue by Southclaws** [uber-go/fx#801]
I've just added a new component to a codebase that uses the OnStart hook but it's not being called at all. The Invoke func is called but the hook isn't and it doesn't seem obvious why.

Here's some code, I have quite a few components in the codebase that are structured the exact same way and they work fine. I thought I understood fx but it seems there's something missing:

```go
func Build() fx.Option {
	return fx.Options(
		fx.Invoke(func(
			lc fx.Lifecycle,
			bs burgershot.Repository,
			users user.Repository,
			forum forum.Repository,
		) *Worker {
			w := &Worker{bs, users, forum}

			zap.L().Debug("invoke bsworker")

			lc.Append(fx.Hook{
				OnStart: w.run,
			})

			return w
		}),
	)
}

func (w *Worker) run(ctx context.Context) error {
	zap.L().Debug("onstart")
	return w.migrateUsers(ctx)
}
```

Here's a similar component that works fine and has done for months:

https://github.com/openmultiplayer/web/blob/master/server/src/serverworker/serverworker.go#L41-L60

Here are some logs, I kept the important parts and removed the noise:

```
2021/11/01 11:48:52 [Fx] PROVIDE	config.Config <= github.com/openmultiplayer/web/server/src/config.New()
2021/11/01 11:48:52 [Fx] PROVIDE	*db.PrismaClient <= github.com/openmultiplayer/web/server/src/db.New()
2021/11/01 11:48:52 [Fx] PROVIDE	forum.Repository <= github.com/openmultiplayer/web/server/src/resources/forum.New()
2021/11/01 11:48:52 [Fx] PROVIDE	user.Repository <= github.com/openmultiplayer/web/server/src/resources/user.New()
2021/11/01 11:48:52 [Fx] PROVIDE	burgershot.Repository <= github.com/openmultiplayer/web/server/src/resources/burgershot.New()
2021/11/01 11:48:52 [Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()

2021/11/01 11:48:52 [Fx] INVOKE		github.com/openmultiplayer/web/server/src/serverworker.Build.func1()
2021/11/01 11:48:52 [Fx] INVOKE		github.com/openmultiplayer/web/server/src/pawndexworker.Build.func1()
2021/11/01 11:48:52 [Fx] INVOKE		github.com/openmultiplayer/web/server/src/bsworker.Build.func1()

2021-11-01T11:48:52.625Z	DEBUG	bsworker/bsworker.go:29	invoke bsworker

2021/11/01 11:48:52 [Fx] START		github.com/openmultiplayer/web/server/src/db.New()
2021/11/01 11:48:52 [Fx] START		github.com/openmultiplayer/web/server/src/mailworker.New()
2021/11/01 11:48:52 [Fx] START		github.com/openmultiplayer/web/server/src/bs.New()
2021/11/01 11:48:52 [Fx] START		github.com/openmultiplayer/web/server/src/api.Build.func3()
2021/11/01 11:48:52 [Fx] START		github.com/openmultiplayer/web/server/src/serverworker.Build.func1()
```

The `invoke bsworker` log entry is called and all the lifecycle hooks for other components are called (databases, the other "worker" I linked above) but no "bsworker` and there are no errors indicating why, it's just silently failing.

Any ideas?

**Comment by Southclaws** [comment]
I've pushed my working copy here: https://github.com/openmultiplayer/web/pull/450/files#diff-74a01ab361f036ccaacc3c875780e8a0bb29446815aff56c5240ae6de3942fef

I really can't see any difference between this new component and the existing ones, I've gone over the fx docs again too.

**Comment by abhinav** [comment]
Hello! So, there's a subtle intricacy in usage of lifecycles that is causing the issue.

pawndexworker returns [pawndexworker.worker.run](https://github.com/openmultiplayer/web/blob/577866a5856bff8a171664f20c315b4b2340ff5b/server/src/pawndexworker/pawndexworker.go#L43) as a hook, which [blocks indefinitely](https://github.com/openmultiplayer/web/blob/577866a5856bff8a171664f20c315b4b2340ff5b/server/src/pawndexworker/pawndexworker.go#L114).

This effectively turns into:

```
pawndexworker.worker.run()
bsworker.worker.run() // never runs because pawndexworker is blocking
```

Fx runs startup hooks in the main goroutine.
The expectation is that startup hooks spawn goroutines for any long-running work.
This separation can be confusing, but is necessary to separate things like startup health checks (that prevent your service from starting up) from just the long running processes of your service.

So to fix this, you likely want to call `w.run` inside a goroutine.
Further, because you want to still be able to stop the worker with OnStop,
you can keep `w.run` unchanged, but use a different context to tell it to stop.

Try something like:

```go
package pawndexworker

func Build() fx.Option {
	return fx.Options(
    // ...
    fx.Invoke(func(...) {
      w := &worker{....}
      
      // This context is associated with the lifetime of the worker.
      // This context is valid as long as the worker should still be running.
      workerCtx, stopWorker := context.WithCancel(context.Background())
      
      lc.Append(fx.Hook{
        OnStart: func(ctx context.Context) error {
          // ^This context specifies how long Fx is willing to wait
          // for pawndexworker to start up. The default is 15 seconds.
          // After 15 seconds, this context becomes invalid,
          // so DO NOT use it for the long-running goroutine.
          //
          // Use it for any operations you need to do at startup which,
          // if they fail, should prevent your service from starting up.
          go w.run(workerCtx)
          return nil
        },
        
        OnStop: func(ctx context.Context) error {
          // Similarly, this context specifies how long Fx is willing to wait
          // for pawndexworker to stop.
          //
          // In this example, I'm just calling stopWorker and exiting,
          // but if we wanted to,
          // we could wait here until w.run finished running.
          stopWorker()
          return nil
        },
      })
    })
  )
}
```

You'll likely want to do something similar for any other hooks that are currently blocking and shouldn't be.

Hope this helped!

**Comment by Southclaws** [comment]
Ah! Thank you so much! This makes total sense now, it was pure fluke that pawndexworker was the last one in the list so it worked and I only discovered this issue when adding a new provider.

It feels like a bit of a footgun, though I notice the ctx in OnStart has a 15 second timeout - it seems I never saw that context get cancelled for the pawndexworker (unless I messed up the context propagation in that worker)

> After 15 seconds, this context becomes invalid

Does this mean the context is cancelled? Because my code has a <-Done() and it will return a context.Cancelled back to OnStart in this case, I would have expected this to make Fx's App error out.

**Comment by abhinav** [comment]
Yeah, the way OnStart hooks plug in is indeed a footgun and one of the more confusing aspects of how Fx lifecycles work. We have some plans/ideas for providing an alternative API that still encourages best practices in the future, but nothing we can commit to yet.

Yeah, the start context times out after 15 seconds. It's not immediately obvious why pawndexworker did not see a context error.
