### ISSUE TITLE
Documentation for fx.As is invalid

### ISSUE THREAD

**Issue by apawelec** [uber-go/fx#810]
Docs shows `fx.As(io.Writer)` but it is illegal expression - it should be `fx.As(new(io.Writer))` (as in unit tests).

**Comment by sywhang** [comment]
hey @apawelec , thanks for reporting this. We've fixed this already in https://github.com/uber-go/fx/pull/806 but we haven't done a release since then. I'll close this issue as it's fixed in master; you should be able to see the updated documentation when we release the next version
