### ISSUE TITLE
In production, disable logging ? Or Change to use logrus and only output errors ?

### ISSUE THREAD

**Issue by iangregsondev** [uber-go/fx#826]
Hi,

I wonder if anyone can help ?

I have everything working but when I build for production the output is still logging all the Fx Uber stuff.

I know I am able to use NopLogger, is this good practice for production ?

I would have preferred maybe to use logrus (the logger I use in my app) and only output errors so that there is no noise.

Is this possible, I checked the docs but I am confused if using NopLogger is a good practice, I would say maybe not because if there is an error then I wouldn't get to see it BUT I presume if I have been able to build it then there is no chance of it giving an error ?

If NopLogger is not good practice, then can I use logrus in place of this and only output Errors ?

Or can I intercept the logs and check some kind of "error level" and use logrus to error out etc..

Any ideas, I am a little confused about the correct direction to take

Thanks in advance

**Comment by sywhang** [comment]
Hey there,

> I know I am able to use NopLogger, is this good practice for production ?

I think this is more of a question not really specific to Fx but production servers in general. Logging in production is indeed an encouraged practice. Configuring an app to use NopLogger is not something you can change halfway down the road, so if your app runs into an issue and you configured to use NopLogger, then you'll need to re-build the application using a Logger and run it again to see what could've caused it. 

That being said, there are very specific cases where you'd want no logs. Say you have an extremely short-lived application (i.e. CLI) that do not need verbose logging and its lifecycle behavior is very well-understood - then you probably do not need a logger. But even many CLI tools come with a flag that turns on the logger (i.e. --verbose, --logs), so there's that.

>  I presume if I have been able to build it then there is no chance of it giving an error ?

Not really, any constructors or hooks you provided could error out when they execute. Or when the app is shutting down, Fx logs any OnStop hooks you have added and can tell you if any of them fail, and where they got added, etc.

> If NopLogger is not good practice, then can I use logrus in place of this and only output Errors ?
> Or can I intercept the logs and check some kind of "error level" and use logrus to error out etc..

Yup, this is possible. Check out the [`fxevent.Logger`](https://pkg.go.dev/go.uber.org/fx@v1.16.0/fxevent#Logger) interface. You can define your own type that implements this interface that uses logrus, and define which `Event`s you want to log. The fxevent package has all the `Event` types that gets logged by fx (i.e. `Invoked`, `Invoking`, `OnStartExecuted`, etc...), so you can choose which ones to log in the `LogEvent` method. 

Hope that helps!
