### ISSUE TITLE
[feat] Dynamically build options

### ISSUE THREAD

**Issue by lookfirst** [uber-go/fx#838]
I created a [discussion](https://github.com/uber-go/fx/discussions/836) that is admittedly kind of confusing, but I think I've solidified what I'd like to see added to fx into something a lot simpler, so I'm filing an issue.

Imagine that you have something generic that runs tasks, but you have different tasks for different machines. You only want to load/provide tasks for the current type of machine. Option groups are a great way to do this, but you can't dynamically create those groups.

What I'd like to see is something like this:

```golang
func myOptionsBuilder(fxprovided Anything) []fx.Option {
}

fx.Options(myOptionsBuilder)
```

This would allow me to dynamically create option groups (in this case, "tasks" are just funcs):

```golang
func buildOptions(tasks []interface{}, groupName string) []fx.Option {
	var options []fx.Option
	for _, t := range tasks {
		options = append(options, fx.Provide(fx.Annotate(t, fx.ResultTags(fmt.Sprintf("group:\"%s\"", groupName)))))
	}
	return options
}
```

Right now, I have to tell fx about all the available options and then choose which ones I want to use during Invoke. This works well...

```golang
type TaskGroup struct {
	fx.In
	ATasks    []*task.Task `group:"a"`
	BTasks   []*task.Task `group:"b"`
	UnknownTasks []*task.Task `group:"unknown"`
}


var AllTasksModule = fx.Options(
	fx.Options(buildOptions(aTasks, "a")...),
	fx.Options(buildOptions(bTasks, "b")...),
	fx.Options(buildOptions(unknownTasks, "unknown")...),
	fx.Invoke(
		func(machine machine.Machine, manager *task.TaskManager, ctxProvider *misc.ContextProvider, group TaskGroup) error {
			var tasks []*task.Task

			if machine.IsA() {
				tasks = group.ATasks
			} else if machine.IsB() {
				tasks = group.BTasks
			} else if machine.IsUnknown() {
				tasks = group.UnknownTasks
			}

			return manager.Start(ctxProvider.Ctx, tasks)
		},
	),
)
```

It would be nicer if I could just tell fx the options I wanted to use.

**Comment by abhinav** [comment]
Hello! I've responded in #836. Closing in favor of that.
