### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by bluebrown** [uber-go/fx#881]
Hi, I found this project, and it looks interesting. I have no clue how to use it, though. It would be nice to have some content in the readme or some examples.

**Comment by bluebrown** [comment]
Well, I just found this. So there is some example https://github.com/uber-go/fx/blob/master/example_test.go

**Comment by abhinav** [comment]
Hello, @bluebrown.

Yes, the bulk of the public documentation of the project is in the [API reference](https://pkg.go.dev/go.uber.org/fx) and [that example test](https://pkg.go.dev/go.uber.org/fx#example-package). 

We're planning on exporting more of our documentation around getting started, how to use it, etc. in the near future.

(Internal issue ref GO-1249)

**Comment by sywhang** [comment]
We've published https://uber-go.github.io/fx/ and we're actively adding contents to it. Closing this issue as done.
