### ISSUE TITLE
Lifecycle not being called

### ISSUE THREAD

**Issue by ainsleyclark** [uber-go/fx#891]
**Describe the bug**
Lifecycle not being called.

**To Reproduce**
```go
func Scratch() error {
	fx.New(fx.Options(
		fx.Provide(TestLifecycle),
		fx.Invoke(func(n *NoOp) {
			fmt.Println("In invoke")
		}),
	))
	return nil
}

type NoOp struct{}

func TestLifecycle(lc fx.Lifecycle) *NoOp {
	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			fmt.Println("In start")
			return nil
		},
		OnStop: func(ctx context.Context) error {
			fmt.Println("In stop")
			return nil
		},
	})
	return &NoOp{}
}
```

**Expected behavior**
Correct me if I'm wrong, but I thought appending a lifecycle to a constructors body would enable us to Ping a database for example, or close one when the program is exited. However `In start` or `In stop` never gets printed, and I'm wondering why?

Here is the output:

```
[Fx] PROVIDE    *cli.NoOp <= github.com//cli.TestLifecycle()
[Fx] PROVIDE    fx.Lifecycle <= go.uber.org/fx.New.func1()
[Fx] PROVIDE    fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
[Fx] PROVIDE    fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
[Fx] INVOKE             github.com/cli.Scratch.func1()
In invoke
```

**Additional context**
N/A

Many thanks in advance.

**Comment by mway** [comment]
Invoked functions are executed _before_ start hooks (because they happen before the application starts, for additional wiring/etc), so you would need to call `Run()` on your `*fx.App` in order to see the start hooks firing.

See [this playground](https://go.dev/play/p/iucGLdt-B5H) for an example.

**Comment by ainsleyclark** [comment]
Thanks! Appreciate your help.
