### ISSUE TITLE
Values provided to a soft value group can depend on the order of fx options

### ISSUE THREAD

**Issue by EstebanOlmedo** [uber-go/fx#911]
Currently the values provided to a `soft` value group can depend on the order of the fx options. For example in the next code:
```go
fx.New(
      fx.Invoke(
	      fx.Annotate(
		      func(s []string) {
			      fmt.Println("Hard: ", s)
		      },
		      fx.ParamTags(`group:"strings"`),
	      ),
      ),
      fx.Invoke(
	      fx.Annotate(
		      func(s []string) {
			      fmt.Println("Soft: ", s)
		      },
		      fx.ParamTags(`group:"strings,soft"`),
	      ),
      ),
      fx.Provide(
	      fx.Annotate(
		      func() string { return "there" },
		      fx.ResultTags(`group:"strings"`),
	      ),
      ),
      fx.Provide(
	      fx.Annotate(
		      func() string { return "hello" },
		      fx.ResultTags(`group:"strings"`),
	      ),
      ),
).Run() 
```
The string slice `s` would be `[]`, which is incorrect. But if you change the position of the `fx.Invoke` options, the slice `s` will be populated with both `"hello"` and `"there"` strings, which are the expected values in the slice.

**Comment by sywhang** [comment]
Actually, this may not be a bug. 

Given how this is implemented, it's an expected behavior.

The thing I am not certain about is if we want such an "ordering" issue. i.e. the users do not have a precise and explicit control over when their Invokes will be called with respect to other functions being Invoked. 

Let's discuss this offline @EstebanOlmedo .

**Comment by sywhang** [comment]
Synced offline. This is the designed behavior. Closing the issue as it's not a real bug.

**Comment by jkanywhere** [comment]
Please clarify, what is the designed behavior and why?

https://go.dev/play/p/umSD0spuotW demonstrates that the order of `fx.Invoke` arguments matters:
If the `soft` invokation is first, it receives an empty value group.

It is not obvious to me why the order should matter. Please help clarify why that is desirable.

```
**** soft before hard ****
[Fx] PROVIDE	string[group = "strings"] <= fx.Annotate(main.run.func1(), fx.ResultTags(["group:\"strings\""])
[Fx] PROVIDE	string[group = "strings"] <= fx.Annotate(main.run.func2(), fx.ResultTags(["group:\"strings\""])
[Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()
[Fx] PROVIDE	fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
[Fx] PROVIDE	fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
[Fx] INVOKE		fx.Annotate(main.main.func1(), fx.ParamTags(["group:\"strings,soft\""])
Soft:  []
[Fx] INVOKE		fx.Annotate(main.main.func2(), fx.ParamTags(["group:\"strings\""])
Hard:  [hello there]
[Fx] RUNNING


**** hard before soft ****
[Fx] PROVIDE	string[group = "strings"] <= fx.Annotate(main.run.func1(), fx.ResultTags(["group:\"strings\""])
[Fx] PROVIDE	string[group = "strings"] <= fx.Annotate(main.run.func2(), fx.ResultTags(["group:\"strings\""])
[Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()
[Fx] PROVIDE	fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
[Fx] PROVIDE	fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
[Fx] INVOKE		fx.Annotate(main.main.func2(), fx.ParamTags(["group:\"strings\""])
Hard:  [hello there]
[Fx] INVOKE		fx.Annotate(main.main.func1(), fx.ParamTags(["group:\"strings,soft\""])
Soft:  [hello there]
[Fx] RUNNING



Program exited.
```

**Comment by sywhang** [comment]
@jkanywhere Thanks for asking this. Let me convert your question into a Discussion and answer it there rather than answering here so that this becomes more discoverable.
